import { RubricData } from './types';

export const CHAPTER_INDEX: string[] = [
  'Mind',
  'Vertigo',
  'Head',
  'Eye',
  'Vision',
  'Ear',
  'Hearing',
  'Nose',
  'Smell',
  'Face',
  'Mouth',
  'Taste',
  'Teeth',
  'Throat',
  'External Throat',
  'Stomach',
  'Abdomen',
  'Hypochondrium',
  'Umbilicus',
  'Bladder',
  'Kidney',
  'Urethra',
  'Urine',
  'Male Genitalia',
  'Female Genitalia',
  'Larynx and Trachea',
  'Respiration',
  'Cough',
  'Expectoration',
  'Chest',
  'Heart',
  'Back',
  'Extremities',
  'Sleep',
  'Chills',
  'Fever',
  'Perspiration',
  'Skin',
  'Generalities',
];

export const CATEGORIES: string[] = [
  'Mind',
  'Head',
  'Eye',
  'Ear',
  'Nose',
  'Throat',
  'Stomach',
  'Abdomen',
  'Stool',
  'Urine',
  'Male',
  'Female',
  'Respiratory',
  'Chest',
  'Heart',
  'Back',
  'Extremities',
  'Skin',
  'Sleep',
  'Chills & Fever',
  'Perspiration',
  'Generalities',
];

export const GENERAL_SUB_CATEGORIES: Record<string, string[]> = {
  'Thermal': ['Hot patient', 'Chilly patient', 'Ambithermal'],
  'Thirst': ['Increased', 'Decreased', 'Thirstless'],
  'Desires': ['Sweets', 'Sour', 'Salty', 'Spicy', 'Fats', 'Cold drinks', 'Hot drinks', 'Eggs', 'Fruits'],
  'Aversions': ['Sweets', 'Sour', 'Salty', 'Meat', 'Milk', 'Fat'],
  'Sleep': ['Sleepless', 'Sleepy', 'Disturbed', 'Awakens at 3AM', 'Awakens at 4AM'],
  'Dreams': ['Anxious', 'Falling', 'Water', 'Fire', 'Death', 'Animals'],
  'Tongue': ['Coated white', 'Coated yellow', 'Clean', 'Dry', 'Trembling', 'Mapped/geographic'],
  'Appetite': ['Increased', 'Decreased', 'Lost', 'Ravenous'],
  'Stool': ['Constipated', 'Loose', 'Diarrhea', 'Alternating'],
  'Menses': ['Profuse', 'Scanty', 'Irregular', 'Painful', 'Early', 'Late', 'Clotted'],
  'Sides': ['Right sided', 'Left sided', 'Left to right', 'Right to left'],
  'Time Modalities': ['< Morning', '< Evening', '< Night', '< Midday', '< 3AM', '> Open air', '> Rest', '> Motion'],
  'Weather': ['< Damp', '< Cold', '< Heat', '< Storm', '< Change of weather'],
};

export const CHAPTER_CATEGORIES: Record<string, string[]> = {
  'Mind': ['Irritability', 'Anxiety', 'Fear', 'Grief', 'Anger', 'Depression', 'Weeping', 'Loquacity', 'Rapid speech', 'Dullness', 'Memory weakness', 'Timidity', 'Suspiciousness', 'Restlessness', 'Aversion to company', 'Desires to be alone', 'Helplessness', 'Hope', 'Indifference', 'Jealousy', 'Mirth', 'Sentimental'],
  'Head': ['Pain - general', 'Pain - temporal', 'Pain - frontal', 'Pain - occipital', 'Pain - vertex', 'Pain - throbbing', 'Pain - pressing', 'Pain - bursting', 'Pain - boring', 'Pain - stitching', 'Pain - splitting', 'Pain - < sun', 'Pain - < noise', 'Pain - < movement', 'Congestion', 'Heaviness', 'Vertigo'],
  'Eye': ['Pain', 'Burning', 'Watering', 'Redness', 'Itching', 'Dim vision', 'Photophobia', 'Lachrymation', 'Dryness', 'Swelling', 'Styes', 'Ulceration', 'Cataract'],
  'Ear': ['Pain', 'Discharge', 'Ringing/Tinnitus', 'Hearing - acute', 'Hearing - diminished', 'Itching', 'Swelling', 'Hardness of hearing'],
  'Nose': ['Coryza', 'Discharge - watery', 'Discharge - thick', 'Sneezing', 'Obstruction', 'Bleeding/Epistaxis', 'Smell - acute', 'Smell - lost', 'Dryness', 'Itching'],
  'Stomach': ['Nausea', 'Vomiting', 'Heartburn', 'Appetite - increased', 'Appetite - decreased', 'Appetite - lost', 'Thirst', 'Craving', 'Aversion', 'Indigestion', 'Eructations', 'Fullness', 'Pain', 'Sour taste'],
  'Abdomen': ['Pain - general', 'Pain - umbilical', 'Pain - hypogastric', 'Pain - hepatic', 'Pain - splenic', 'Bloating/Distension', 'Flatulence', 'Hardness', 'Tenderness', 'Gurgling'],
  'Skin': ['Itching', 'Burning', 'Dry', 'Eruptions', 'Urticaria', 'Eczema', 'Psoriasis', 'Warts', 'Ulcers', 'Perspiration'],
  'Extremities': ['Pain - joints', 'Pain - limbs', 'Weakness', 'Trembling', 'Cramps', 'Stiffness', 'Swelling', 'Numbness', 'Coldness', 'Restlessness'],
  'Respiratory': ['Difficulty breathing', 'Asthma', 'Wheezing', 'Cough - dry', 'Cough - productive', 'Expectoration', 'Suffocation', 'Chest tightness'],
  'Sleep': ['Sleeplessness', 'Sleepy', 'Disturbed', 'Awakens early', 'Sleep position', 'Dreams', 'Snoring', 'Sleep walking'],
  'Chills': ['Chilly', 'Shivering', 'Chills - periodic', 'Chills - from draft', 'Chills - after drinking'],
  'Fever': ['High fever', 'Low fever', 'Intermittent', 'Remittent', 'Morning fever', 'Evening fever', 'Night fever', 'Sweat with fever', 'Thirst during fever'],
  'Perspiration': ['Profuse', 'Scanty', 'Offensive', 'Sour', 'Cold', 'Hot', 'Night sweats', 'Under arms', 'On palms', 'On soles'],
  'Generalities': ['Aggravation', 'Amelioration', 'Constitution', 'Sides', 'Weather', 'Time', 'Motion', 'Rest', 'Position'],
  'Female Genitalia': ['Menses - profuse', 'Menses - scanty', 'Menses - irregular', 'Menses - painful', 'Menses - early', 'Menses - late', 'Leucorrhea', 'Pain - ovarian', 'Pain - uterine', 'Menopause'],
  'Male Genitalia': ['Pain', 'Weakness', 'Emissions', 'Desire - increased', 'Desire - decreased', 'Swelling', 'Induration'],
  'Throat': ['Pain', 'Dryness', 'Swelling', 'Difficulty swallowing', 'Tonsillitis', 'Foreign body sensation', 'Burning', 'Redness'],
  'Chest': ['Pain', 'Tightness', 'Congestion', 'Palpitation', 'Oppression', 'Weakness'],
  'Back': ['Pain - cervical', 'Pain - dorsal', 'Pain - lumbar', 'Pain - sacral', 'Stiffness', 'Weakness'],
};

export const REPERTORY_DATA: RubricData[] = [
  {
    id: 'mind-irritability',
    chapter: 'Mind',
    rubrics: [
      { id: 'mind-1', text: 'Irritability', chapter: 'Mind', remedies: ['Nux Vomica', 'Chamomilla', 'Staphysagria', 'Natrum Mur', 'Bryonia', 'Lycopodium'], grade: 3 },
      { id: 'mind-2', text: 'Irritability - with headache', chapter: 'Mind', remedies: ['Nux Vomica', 'Bryonia'], grade: 2 },
      { id: 'mind-3', text: 'Anxiety', chapter: 'Mind', remedies: ['Aconite', 'Argentum Nitricum', 'Arsenicum Album', 'Gelsemium', 'Ignatia', 'Kali Arsenicosum', 'Phosphorus'], grade: 3 },
      { id: 'mind-4', text: 'Anxiety - with palpitations', chapter: 'Mind', remedies: ['Aconite', 'Argentum Nitricum', 'Arsenicum Album', 'Phosphorus'], grade: 2 },
      { id: 'mind-5', text: 'Fear - of death', chapter: 'Mind', remedies: ['Aconite', 'Arsenicum Album', 'Phosphorus', 'Lachesis'], grade: 3 },
      { id: 'mind-6', text: 'Fear - of death - predicts time', chapter: 'Mind', remedies: ['Aconite', 'Arsenicum Album'], grade: 2 },
      { id: 'mind-7', text: 'Grief - silent', chapter: 'Mind', remedies: ['Natrum Mur', 'Ignatia', 'Phosphoric Acid', 'Sepia'], grade: 3 },
      { id: 'mind-8', text: 'Depression', chapter: 'Mind', remedies: ['Aurum', 'Ignatia', 'Natrum Mur', 'Phosphorus', 'Pulsatilla', 'Sepia'], grade: 3 },
      { id: 'mind-9', text: 'Weeping', chapter: 'Mind', remedies: ['Pulsatilla', 'Ignatia', 'Natrum Mur', 'Sepia', 'Aconite'], grade: 3 },
      { id: 'mind-10', text: 'Restlessness', chapter: 'Mind', remedies: ['Arsenicum Album', 'Rhus Tox', 'Aconite', 'Zincum'], grade: 3 },
      { id: 'mind-11', text: 'Anger - violent', chapter: 'Mind', remedies: ['Nux Vomica', 'Chamomilla', 'Staphysagria', 'Belladonna'], grade: 3 },
      { id: 'mind-12', text: 'Memory - weakness of', chapter: 'Mind', remedies: ['Baryta Carb', 'Lycopodium', 'Silicea', 'Syphilinum'], grade: 2 },
    ],
  },
  {
    id: 'head-pain',
    chapter: 'Head',
    rubrics: [
      { id: 'head-1', text: 'Headache - throbbing', chapter: 'Head', remedies: ['Belladonna', 'Natrum Mur', 'Sanguinaria', 'Glonoine', 'Nux Vomica'], grade: 3 },
      { id: 'head-2', text: 'Headache - bursting', chapter: 'Head', remedies: ['Belladonna', 'Natrum Mur', 'Nux Vomica', 'Lycopodium'], grade: 2 },
      { id: 'head-3', text: 'Headache - frontal', chapter: 'Head', remedies: ['Natrum Mur', 'Bryonia', 'Nux Vomica', 'Sanguinaria', 'Spigelia'], grade: 3 },
      { id: 'head-4', text: 'Headache - temporal', chapter: 'Head', remedies: ['Natrum Mur', 'Crocus Sativus', 'Lachesis', 'Sanguinaria'], grade: 2 },
      { id: 'head-5', text: 'Headache - occipital', chapter: 'Head', remedies: ['Silicea', 'Lycopodium', 'Sepia', 'Cimicifuga'], grade: 2 },
      { id: 'head-6', text: 'Headache - vertex', chapter: 'Head', remedies: ['Bryonia', 'China', 'Thuja', 'Natrum Mur'], grade: 2 },
      { id: 'head-7', text: 'Headache - < sun', chapter: 'Head', remedies: ['Natrum Mur', 'Belladonna', 'Lachesis', 'Carcinosinum'], grade: 3 },
      { id: 'head-8', text: 'Headache - < noise', chapter: 'Head', remedies: ['Natrum Mur', 'Nux Vomica', 'Bryonia', 'Belladonna'], grade: 2 },
      { id: 'head-9', text: 'Headache - < movement', chapter: 'Head', remedies: ['Bryonia', 'Belladonna'], grade: 2 },
      { id: 'head-10', text: 'Headache - > sleep', chapter: 'Head', remedies: ['Natrum Mur', 'Nux Vomica', 'Sepia'], grade: 2 },
      { id: 'head-11', text: 'Headache - with nausea', chapter: 'Head', remedies: ['Iris Versicolor', 'Natrum Mur', 'Nux Vomica', 'Sanguinaria', 'Cyclamen'], grade: 3 },
      { id: 'head-12', text: 'Headache - with vomiting', chapter: 'Head', remedies: ['Iris Versicolor', 'Sanguinaria', 'Cyclamen', 'Ipecac'], grade: 2 },
      { id: 'head-13', text: 'Headache - migraine', chapter: 'Head', remedies: ['Natrum Mur', 'Sanguinaria', 'Iris Versicolor', 'Crocus Sativus', 'Spigelia', 'Sepia'], grade: 3 },
    ],
  },
  {
    id: 'stomach-nausea',
    chapter: 'Stomach',
    rubrics: [
      { id: 'stom-1', text: 'Nausea', chapter: 'Stomach', remedies: ['Ipecac', 'Nux Vomica', 'Antim Crud', 'Bryonia', 'Pulsatilla', 'Sepia', 'Arsenicum Album'], grade: 3 },
      { id: 'stom-2', text: 'Nausea - with headache', chapter: 'Stomach', remedies: ['Iris Versicolor', 'Sanguinaria', 'Cyclamen', 'Natrum Mur', 'Nux Vomica'], grade: 2 },
      { id: 'stom-3', text: 'Vomiting', chapter: 'Stomach', remedies: ['Ipecac', 'Arsenicum Album', 'Phosphorus', 'Bryonia', 'Zincum', 'Cocculus'], grade: 3 },
      { id: 'stom-4', text: 'Heartburn', chapter: 'Stomach', remedies: ['Robinia', 'Arsenicum Album', 'Carbo Veg', 'Nux Vomica', 'Pulsatilla'], grade: 3 },
      { id: 'stom-5', text: 'Appetite - increased', chapter: 'Stomach', remedies: ['Iodum', 'Phosphorus', 'Lycopodium', 'Chelidonium', 'China', 'Sulphur', 'Tuberculinum'], grade: 3 },
      { id: 'stom-6', text: 'Appetite - decreased', chapter: 'Stomach', remedies: ['Nux Vomica', 'Bryonia', 'Carbo Veg', 'Lycopodium', 'Phosphorus', 'Pulsatilla', 'Sepia'], grade: 3 },
      { id: 'stom-7', text: 'Thirst - increased', chapter: 'Stomach', remedies: ['Arsenicum Album', 'Phosphorus', 'Bryonia', 'Lycopodium', 'Natrum Mur', 'Sulphur', 'Tuberculinum'], grade: 3 },
      { id: 'stom-8', text: 'Thirst - thirstless', chapter: 'Stomach', remedies: ['Pulsatilla', 'Antim Crud', 'Apis', 'Calcarea Carb', 'Gelsemium'], grade: 3 },
      { id: 'stom-9', text: 'Desires - sour things', chapter: 'Stomach', remedies: ['Antim Crud', 'Tuberculinum', 'Hepar Sulph', 'Sepia', 'Argentum Nitricum'], grade: 2 },
      { id: 'stom-10', text: 'Desires - sweets', chapter: 'Stomach', remedies: ['Argentum Nitricum', 'Calcare Carb', 'Lycopodium', 'Phosphorus', 'Sulphur', 'Tuberculinum'], grade: 3 },
      { id: 'stom-11', text: 'Desires - spicy food', chapter: 'Stomach', remedies: ['Nux Vomica', 'Phosphorus', 'Sulphur'], grade: 2 },
      { id: 'stom-12', text: 'Aversions - fats', chapter: 'Stomach', remedies: ['Pulsatilla', 'Carbo Veg', 'Antim Crud', 'Calcarea Carb', 'Sepia'], grade: 2 },
    ],
  },
  {
    id: 'extremities-joints',
    chapter: 'Extremities',
    rubrics: [
      { id: 'ext-1', text: 'Pain - joints', chapter: 'Extremities', remedies: ['Bryonia', 'Rhus Tox', 'Arnica', 'Bellis Perennis', 'Ledum', 'Pulsatilla', 'Ruta', 'Sulphur'], grade: 3 },
      { id: 'ext-2', text: 'Pain - joints - < movement', chapter: 'Extremities', remedies: ['Bryonia'], grade: 3 },
      { id: 'ext-3', text: 'Pain - joints - > movement', chapter: 'Extremities', remedies: ['Rhus Tox', 'Ferrum Phos'], grade: 3 },
      { id: 'ext-4', text: 'Stiffness', chapter: 'Extremities', remedies: ['Rhus Tox', 'Bryonia', 'Arnica', 'Cimicifuga', 'Sanguinaria', 'Sulphur'], grade: 3 },
      { id: 'ext-5', text: 'Weakness', chapter: 'Extremities', remedies: ['Gelsemium', 'Phosphorus', 'Arsenicum Album', 'Cocculus', 'Sepia', 'Causticum'], grade: 3 },
      { id: 'ext-6', text: 'Cramps', chapter: 'Extremities', remedies: ['Cuprum Met', 'Cicuta', 'Magnesia Phos', 'Nux Vomica', 'Secale'], grade: 2 },
      { id: 'ext-7', text: 'Trembling', chapter: 'Extremities', remedies: ['Agaricus', 'Gelsemium', 'Zincum', 'Phosphorus', 'Silicea', 'Thuja'], grade: 2 },
      { id: 'ext-8', text: 'Swelling - joints', chapter: 'Extremities', remedies: ['Apis', 'Bryonia', 'Ledum', 'Pulsatilla', 'Rhus Tox', 'Ruta', 'Sulphur'], grade: 3 },
    ],
  },
  {
    id: 'sleep-dreams',
    chapter: 'Sleep',
    rubrics: [
      { id: 'sleep-1', text: 'Sleeplessness', chapter: 'Sleep', remedies: ['Coffea', 'Nux Vomica', 'Arsenicum Album', 'Aconite', 'Lachesis', 'Sulphur', 'Zincum', 'Opium', 'Passiflora'], grade: 3 },
      { id: 'sleep-2', text: 'Sleeplessness - from thoughts', chapter: 'Sleep', remedies: ['Coffea', 'Nux Vomica', 'Ignatia', 'Thuja'], grade: 2 },
      { id: 'sleep-3', text: 'Sleeplessness - after midnight', chapter: 'Sleep', remedies: ['Lachesis', 'Sulphur', 'Medorrhinum', 'Syphilinum', 'Arsenicum Album'], grade: 3 },
      { id: 'sleep-4', text: 'Sleepiness', chapter: 'Sleep', remedies: ['Nux Moschata', 'Opium', 'Phosphorus', 'Sulphur', 'Antim Crud', 'Gelsemium'], grade: 2 },
      { id: 'sleep-5', text: 'Dreams - anxious', chapter: 'Sleep', remedies: ['Aconite', 'Arsenicum Album', 'Ignatia', 'Kali Phos', 'Phosphorus', 'Thuja'], grade: 2 },
      { id: 'sleep-6', text: 'Dreams - vivid', chapter: 'Sleep', remedies: ['Lachesis', 'Cannabis Indica', 'Thuja', 'Nitric Acid', 'Phosphorus'], grade: 2 },
    ],
  },
  {
    id: 'respiratory-cough',
    chapter: 'Respiratory',
    rubrics: [
      { id: 'resp-1', text: 'Cough - dry', chapter: 'Respiratory', remedies: ['Belladonna', 'Bryonia', 'Drosera', 'Spongia', 'Coccus Cacti', 'Rumex', 'Aconite'], grade: 3 },
      { id: 'resp-2', text: 'Cough - loose', chapter: 'Respiratory', remedies: ['Antim Tart', 'Bryonia', 'Ipecac', 'Kali Bich', 'Pulsatilla', 'Sepia', 'Stannum'], grade: 3 },
      { id: 'resp-3', text: 'Cough - > eating', chapter: 'Respiratory', remedies: ['Chelidonium', 'Natrum Sulph'], grade: 2 },
      { id: 'resp-4', text: 'Difficult breathing', chapter: 'Respiratory', remedies: ['Arsenicum Album', 'Antim Tart', 'Ipecac', 'Lachesis', 'Phosphorus', 'Spongia'], grade: 3 },
      { id: 'resp-5', text: 'Wheezing', chapter: 'Respiratory', remedies: ['Arsenicum Album', 'Ipecac', 'Spongia', 'Antim Tart', 'Natrum Sulph'], grade: 2 },
      { id: 'resp-6', text: 'Cough - < night', chapter: 'Respiratory', remedies: ['Arsenicum Album', 'Drosera', 'Phosphorus', 'Spongia', 'Rumex'], grade: 3 },
    ],
  },
];
