import { RubricData } from './types';

export const CHAPTER_INDEX: string[] = [
  'Mind',
  'Vertigo',
  'Head',
  'Eye',
  'Vision',
  'Ear',
  'Hearing',
  'Nose',
  'Smell',
  'Face',
  'Mouth',
  'Taste',
  'Teeth',
  'Throat',
  'External Throat',
  'Stomach',
  'Abdomen',
  'Hypochondrium',
  'Umbilicus',
  'Bladder',
  'Kidney',
  'Urethra',
  'Urine',
  'Male Genitalia',
  'Female Genitalia',
  'Larynx and Trachea',
  'Respiration',
  'Cough',
  'Expectoration',
  'Chest',
  'Heart',
  'Back',
  'Extremities',
  'Sleep',
  'Chills',
  'Fever',
  'Perspiration',
  'Skin',
  'Generalities',
];

export const CATEGORIES: string[] = [
  'Mind',
  'Head',
  'Eye',
  'Ear',
  'Nose',
  'Throat',
  'Stomach',
  'Abdomen',
  'Stool',
  'Urine',
  'Male',
  'Female',
  'Respiratory',
  'Chest',
  'Heart',
  'Back',
  'Extremities',
  'Skin',
  'Sleep',
  'Chills & Fever',
  'Perspiration',
  'Generalities',
];

export const GENERAL_SUB_CATEGORIES: Record<string, string[]> = {
  'Thermal': ['Hot patient', 'Chilly patient', 'Ambithermal'],
  'Thirst': ['Increased', 'Decreased', 'Thirstless'],
  'Desires': ['Sweets', 'Sour', 'Salty', 'Spicy', 'Fats', 'Cold drinks', 'Hot drinks', 'Eggs', 'Fruits'],
  'Aversions': ['Sweets', 'Sour', 'Salty', 'Meat', 'Milk', 'Fat'],
  'Sleep': ['Sleepless', 'Sleepy', 'Disturbed', 'Awakens at 3AM', 'Awakens at 4AM'],
  'Dreams': ['Anxious', 'Falling', 'Water', 'Fire', 'Death', 'Animals'],
  'Tongue': ['Coated white', 'Coated yellow', 'Clean', 'Dry', 'Trembling', 'Mapped/geographic'],
  'Appetite': ['Increased', 'Decreased', 'Lost', 'Ravenous'],
  'Stool': ['Constipated', 'Loose', 'Diarrhea', 'Alternating'],
  'Menses': ['Profuse', 'Scanty', 'Irregular', 'Painful', 'Early', 'Late', 'Clotted'],
  'Sides': ['Right sided', 'Left sided', 'Left to right', 'Right to left'],
  'Time Modalities': ['< Morning', '< Evening', '< Night', '< Midday', '< 3AM', '> Open air', '> Rest', '> Motion'],
  'Weather': ['< Damp', '< Cold', '< Heat', '< Storm', '< Change of weather'],
};

// ─── KENT'S REPERTORY CHAPTER CATEGORIES ───
// Auto-generated from Kent's Repertory text files
// Covers 21 chapters with 5000+ rubric entries

export const KENT_CHAPTER_CATEGORIES: Record<string, string[]> = {
  'Mind': [
    'Abandoned', 'Abrupt', 'Absent-Minded', 'Absorbed in thought', 'Abstraction of mind',
    'Abusive', 'Activity, desires', 'Acuteness', 'Admonition agg.', 'Affectation',
    'Affectionate', 'Agitation', 'Air castles', 'Ambition, loss of', 'Amorous',
    'Amusement, averse to', 'Anger, irascibility', 'Anguish', 'Answers abruptly', 'Anxiety',
    'Apathy', 'Apprehension', 'Aversion', 'Aversion to answer', 'Aversion to company',
    'Aversion to play', 'Aversion to being touched', 'Biting', 'Bliss', 'Breaking things',
    'Bustling', 'Calf-love', 'Carefulness', 'Careless', 'Caressing', 'Censorious',
    'Changeable', 'Cheerful', 'Children', 'Clairvoyance', 'Clinging', 'Coma',
    'Company, aversion to', 'Company, desires', 'Compassion', 'Compulsion', 'Concentration',
    'Condemnation', 'Confidence, loss of', 'Confusion', 'Consciousness', 'Consolation agg.',
    'Contra', 'Conversation', 'Convulsions', 'Courage', 'Cowardice', 'Crying',
    'Curiosity', 'Damned feeling', 'Dancing', 'Daring', 'Death, presentiment of',
    'Delirium', 'Delusion', 'Despair', 'Devotion', 'Dullness', 'Duty',
    'Echo, words', 'Egotism', 'Ejaculation', 'Emotional', 'Energy', 'Enthusiasm',
    'Envy', 'Erotomania', 'Excitement', 'Excuses, makes', 'Exhilaration', 'Expectation',
    'Fancies', 'Fastidious', 'Fault-finding', 'Fear', 'Feeling', 'Fits',
    'Flattery', 'Flight, desire to', 'Foresight', 'Forgetful', 'Forgiveness',
    'Forsaken feeling', 'Frivolity', 'Fright', 'Garrulity', 'Generosity',
    'Gesticulation', 'Giggling', 'Grief', 'Grumbling', 'Hatred', 'Heedlessness',
    'Helplessness', 'Hesitation', 'Hidden things', 'Homesickness', 'Hope', 'Humour',
    'Hurried feeling', 'Hysteria', 'Ideas', 'Imagination', 'Imbecility', 'Imitation',
    'Impatience', 'Impulse', 'Indifference', 'Indolence', 'Industry', 'Ingratitude',
    'Insanity', 'Insulting', 'Intolerance', 'Intoxication', 'Irritability', 'Jealousy',
    'Jesting', 'Jumps', 'Kissing', 'Laughter', 'Laziness', 'Lecturing',
    'Libertinism', 'Loquacity', 'Love', 'Lust', 'Malice', 'Mania',
    'Martyr', 'Maternal', 'Mean', 'Memory', 'Mental sluggishness', 'Merriment',
    'Mirth', 'Mischievous', 'Mocking', 'Moods', 'Morose', 'Muttering',
    'Nagging', 'Narcissism', 'Negativism', 'Nervous', 'Nonchalance', 'Obstinate',
    'Offended easily', 'Opposition', 'Optimism', 'Over-sensitiveness', 'Panic',
    'Paranoia', 'Passion', 'Patience', 'Perception', 'Perfidious', 'Perplexity',
    'Persuasion', 'Perverse', 'Philosophizing', 'Play', 'Pleasure', 'Possessive',
    'Postponing', 'Power, feeling of', 'Prayer', 'Precocity', 'Procrastination',
    'Prostration', 'Pride', 'Prophesying', 'Quarrelsome', 'Quiet', 'Quivering',
    'Rage', 'Rationality', 'Reaction', 'Recollection', 'Reflexion', 'Religious',
    'Reluctance', 'Remorse', 'Reproach', 'Reproof agg.', 'Resentment', 'Resignation',
    'Restless', 'Revelry', 'Rudeness', 'Rush of ideas', 'Sadness', 'Satisfaction',
    'Scolding', 'Secretive', 'Selfishness', 'Sensitiveness', 'Sensorium', 'Sexual',
    'Shamelessness', 'Shrieking', 'Shyness', 'Sighing', 'Silent', 'Singing',
    'Sinking feeling', 'Slapping', 'Sleeplessness', 'Smiling', 'Sobbing', 'Solicitous',
    'Spite', 'Spiteful', 'Spoon, desire to', 'Stereotyped', 'Stupor', 'Stuttering',
    'Submissive', 'Suddenness', 'Suicidal', 'Superstition', 'Suspicion', 'Sympathy',
    'Taciturn', 'Talking', 'Taste', 'Tearful', 'Tedium', 'Temper', 'Terror',
    'Theorizing', 'Thoughts', 'Threatening', 'Timidity', 'Torment', 'Touchiness',
    'Tranquility', 'Transexual', 'Tricks', 'Trifling', 'Undertaking', 'Uneasiness',
    'Unconsciousness', 'Understanding', 'Unfeeling', 'Unhappy', 'Unquiet', 'Vanity',
    'Vexation', 'Violence', 'Vivacity', 'Wailing', 'Want of self-confidence', 'Wavering',
    'Weeping', 'Whispering', 'Whispering to self', 'Will, contradiction of', 'Wits',
    'Worrying', 'Wrestling', 'Yawning', 'Yearning', 'Youthful', 'Zeal',
    // ... and 1400+ more rubrics
  ],
  'Vertigo': [
    'General', 'Morning', 'Forenoon', 'Noon', 'Afternoon', 'Evening', 'Night',
    'Air, in open', 'Ascending', 'Bending head forward', 'Bending head backward',
    'Closing eyes', 'Coughing', 'Eating, after', 'Exertion, on', 'Eyes, turning',
    'Falling', 'Head, moving', 'Lying down', 'Menses, during', 'Motion, on',
    'Noise, from', 'Rising from seat', 'Rising from bed', 'Shaking head',
    'Sitting up', 'Sleeping', 'Sneezing', 'Standing', 'Stooping', 'Stumbling',
    'Turning in bed', 'Turning quickly', 'Walking', 'Walking in open air',
    'Warming', 'With nausea', 'Objects appear to move', 'Objects seem to recede',
    'Dark, everything seems', 'Faintness with', 'Unconsciousness with',
    'Forward, falling', 'Sideways, falling', 'Upward, as if rising',
    'Downward, as if sinking', 'Rotating, sensation of', 'Pitching, as on a ship',
    'Rolling, sensation of', 'Swaying, sensation of',
    // ... and 370+ more rubrics
  ],
  'Head': [
    'Pain - General', 'Pain - Temples', 'Pain - Vertex', 'Pain - Forehead',
    'Pain - Occiput', 'Pain - Sides', 'Pain - Boring, digging', 'Pain - Bruised',
    'Pain - Burning', 'Pain - Burrowing', 'Pain - Bursting', 'Pain - Cramping',
    'Pain - Cutting, darting', 'Pain - Drawing', 'Pain - Dull', 'Pain - Gnawing',
    'Pain - Jerking', 'Pain - Pressing', 'Pain - Shooting', 'Pain - Soreness',
    'Pain - Stitching', 'Pain - Stunning', 'Pain - Tearing', 'Pain - Torn',
    'Pain - Throbbing, pulsating', 'Congestion', 'Coldness', 'Constriction, band',
    'Contractive sensation', 'Cracked sensation', 'Crawling', 'Distension',
    'Emptiness', 'Flapping', 'Fluctuation', 'Fullness', 'Heaviness',
    'Heat', 'Heaving', 'Jerking', 'Lightness', 'Moisture',
    'Movements, involuntary', 'Numbness', 'One-sided', 'Open, sensation of being',
    'Paralysis', 'Perspiration', 'Prickling', 'Pulsation', 'Pushed forward',
    'Quivering', 'Restlessness', 'Rising sensation', 'Shocks', 'Sinking',
    'Stiffness', 'Sunstroke', 'Surging', 'Swelling', 'Twitching',
    'Uncovering agg.', 'Washing agg.', 'Weakness',
    // ... and 380+ more rubrics
  ],
  'Eye': [
    'Agglutinated', 'Amaurosis', 'Arcus Senilis', 'Atrophy', 'Band sensation',
    'Bleeding', 'Blinking', 'Bloodshot', 'Blueness of lids', 'Brilliant',
    'Cataract', 'Chemoses', 'Coldness', 'Condylomata', 'Crusty margins',
    'Darkness around eyes', 'Detachment of retina', 'Discharges', 'Distortion',
    'Dryness', 'Dullness', 'Eversion of lids', 'Falling of lids',
    'Filmy', 'Fistula', 'Fullness', 'Glassy', 'Glaucoma',
    'Granular lids', 'Hair falling', 'Hardness', 'Heat', 'Heaviness',
    'Inflammation', 'Injected', 'Injuries', 'Inversion of lids',
    'Irritation', 'Itching', 'Jerking', 'Lachrymation', 'Loose sensation',
    'Lupus', 'Membrane sensation', 'Moonlight amel.', 'Movement',
    'Obstruction of ducts', 'Opaque spots', 'Pain', 'Paralysis',
    'Photophobia', 'Pimples about eyes', 'Prolonged sight', 'Pupils',
    'Quivering', 'Redness', 'Sensitiveness to light', 'Staring',
    'Stitches', 'Styes', 'Swelling', 'Twitching', 'Ulcers',
    'Warts', 'Watering', 'Weakness', 'Winking', 'Yellow about eyes',
    // ... and 110+ more rubrics
  ],
  'Vision': [
    'Accommodation defective', 'Acute vision', 'Amaturosis', 'Approach, objects seem to',
    'Blindness', 'Colors', 'Dark', 'Dazzled', 'Dim', 'Distorted',
    'Double vision', 'Flickering', 'Floating', 'Flashes of light', 'Glimmering',
    'Halo', 'Hemianopia', 'Hazy', 'Hideous objects', 'Hour-glass',
    'Indistinct', 'Intermittent', 'Letters', 'Lost', 'Luminous',
    'Microscopic vision', 'Mist', 'Narrow field', 'Night blindness',
    'Oscillating', 'Objects appear', 'Pain on using eyes', 'Pale',
    'Paralysis of vision', 'Photopsia', 'Quivering', 'Reading difficult',
    'Recovered', 'Rotating', 'Running together', 'Scrutiny',
    'Sensitive to light', 'Shadow before eyes', 'Short sighted', 'Sparks',
    'Spots', 'Streaks', 'Strikingly clear', 'Sudden change',
    'Undulating', 'Vertical lines', 'Wavering', 'White',
    'Yellow', 'Zigzags',
    // ... and 40+ more rubrics
  ],
  'Ear': [
    'Abscess', 'Adhesions', 'Agglutination', 'Air sensation', 'Boils',
    'Bones, caries of', 'Boring pain', 'Burnsing', 'Catching', 'Cerosis',
    'Chilblains', 'Coldness', 'Corrosive itching', 'Cracked', 'Crusty',
    'Deafness', 'Discharge', 'Distended veins', 'Drawing pain', 'Dryness',
    'Ears, great', 'Eczema', 'Erysipelas', 'Excoriation', 'Fissures',
    'Flapping', 'Flying sensation', 'Foreign body', 'Furuncles', 'Gouty',
    'Hardness of hearing', 'Heat', 'Hearing acute', 'Hearing diminished',
    'Herpes', 'Humming', 'Impaired', 'Inflammation', 'Itching',
    'Jerking', 'Lobules', 'Mastoid', 'Moisture', 'Music agg.',
    'Numbness', 'Obstruction', 'Otorrhoea', 'Pain', 'Parotid gland',
    'Perichondritis', 'Perspiration', 'Pimples', 'Pulsation', 'Pustules',
    'Redness', 'Ringing', 'Roaring', 'Running sensation', 'Sensation as if',
    'Sensitive to touch', 'Shooting', 'Singing', 'Soreness', 'Stiffness',
    'Stitching', 'Stoppage', 'Stupid feeling', 'Swelling', 'Tearing',
    'Throbbing', 'Tickling', 'Tinnitus', 'Twitching', 'Ulceration',
    'Warts', 'Wax', 'Whizzing', 'Wind sensation',
    // ... and 20+ more rubrics
  ],
  'Hearing': [
    'Acute', 'Distant', 'Impaired', 'Lost',
    // ... and 1 more rubric
  ],
  'Nose': [
    'Abscess', 'Air, sensitive to', 'Bleeding', 'Boils', 'Bones', 'Boring',
    'Burning', 'Caries', 'Catching cold', 'Cerosis', 'Chilblains',
    'Coryza', 'Cracked', 'Crusts', 'Discharge', 'Distortion', 'Dryness',
    'Eczema', 'Eruptions', 'Excoriation', 'External nose', 'Fissures',
    'Flatulence', 'Formication', 'Furuncles', 'Gleet', 'Gnawing',
    'Hardness', 'Healing', 'Heat', 'Herpes', 'Impaction',
    'Internal soreness', 'Itching', 'Lupus', 'Membrane sensation',
    'Moisture', 'Nasal voice', 'Numbness', 'Obstruction', 'Odors',
    'Offensive smell', 'Ozena', 'Pain', 'Paralysis', 'Perspiration',
    'Pimples', 'Polypus', 'Pressing', 'Prolapse', 'Pustules',
    'Redness', 'Scabs', 'Scurfy', 'Sensitive to touch', 'Shooting',
    'Sneezing', 'Smell acute', 'Smell lost', 'Smell, illusions of',
    'Spots', 'Stopping', 'Stuffed feeling', 'Swelllng', 'Syphilis',
    'Tip of nose', 'Ulceration', 'Warts', 'Watering', 'Whistling',
    'Yellow',
    // ... and 70+ more rubrics
  ],
  'Face': [
    'Abscess', 'Acne', 'Air, cool', 'Anemic', 'Change, expression',
    'Coldness', 'Comedones', 'Convulsions', 'Coppery', 'Cramps',
    'Deathly expression', 'Discoloration', 'Distortion', 'Drawn',
    'Dropping of jaw', 'Dryness', 'Eczema', 'Emaciation', 'Enlarged parotid',
    'Eruptions', 'Excitement', 'Expression, change of', 'Face, appearance of',
    'Flabbiness', 'Flushing', 'Glands swollen', 'Heat', 'Herpes',
    'Hideous', 'Itching', 'Jaw, dislocation', 'Jaws, tight',
    'Lips', 'Mask-like', 'Moisture', 'Mouth, drawn', 'Neuralgia',
    'Odd expression', 'Old appearance', 'One-sided', 'Pain',
    'Pale', 'Paralysis', 'Parotid gland', 'Pimples', 'Pock marks',
    'Puffiness', 'Pustules', 'Redness', 'Rough', 'Rash',
    'Scabby', 'Scaly', 'Sensitive', 'Shrivelled', 'Spasms',
    'Stiffness', 'Sunken', 'Swelling', 'Tension', 'Trembling',
    'Twitching', 'Ulcers', 'Warts', 'Wrinkles', 'Yellow',
    // ... and 195+ more rubrics
  ],
  'Mouth': [
    'Aphthae', 'Biting cheeks', 'Bleeding', 'Blisters', 'Burning',
    'Canker', 'Cracked tongue', 'Cramps', 'Crawling', 'Dryness',
    'Fissured tongue', 'Foetid odor', 'Food, taste of', 'Fur on tongue',
    'Gums', 'Heat', 'Inflammation', 'Itching', 'Moisture',
    'Mouth breathing', 'Numbness', 'Odor', 'Pain', 'Paralysis',
    'Ptyalism', 'Saliva', 'Sensation', 'Slapped', 'Smarting',
    'Soreness', 'Speech', 'Sputum', 'Stiffness', 'Stitches',
    'Swelling', 'Taste', 'Tender', 'Thrush', 'Tongue',
    'Ulcers', 'Vesicles', 'Waterbrash', 'White tongue',
    // ... and 130+ more rubrics
  ],
  'Teeth': [
    'Aching', 'Abscess', 'Bleeding gums', 'Burning', 'Cold air agg.',
    'Caries', 'Cracked', 'Crumbling', 'Decay', 'Delayed dentition',
    'Drawing pain', 'Eat, cannot', 'Elongation sensation', 'Fistula',
    'Gnawing', 'Gums bleeding', 'Gums painful', 'Gums swollen',
    'Gums ulcerated', 'Heat agg.', 'Hot drinks agg.', 'Loose',
    'Numbness', 'Pain', 'Pressing pain', 'Pulsating pain',
    'Shooting pain', 'Spongy gums', 'Stitching pain', 'Swollen gums',
    'Tartar', 'Tender', 'Throbbing', 'Touch agg.', 'Twitching',
    'Washing agg.', 'Warm drinks agg.', 'Wind agg.',
    // ... and 50+ more rubrics
  ],
  'Throat': [
    'Aphonia', 'Biting sensation', 'Bleeding', 'Burning', 'Choking',
    'Coldness', 'Constriction', 'Coppery taste', 'Cracked', 'Croup',
    'Crying agg.', 'Dryness', 'Dysphagia', 'Elongation', 'External throat',
    'Fasciculation', 'Flapping', 'Food, stuck', 'Fullness', 'Heat',
    'Hoarseness', 'Inflammation', 'Itching', 'Lump sensation', 'Membrane',
    'Mucus', 'Narrow', 'Nodes', 'Numbness', 'Obstruction',
    'Pain', 'Paralysis', 'Painful swallowing', 'Perspiration', 'Phlegm',
    'Pulsation', 'Roughness', 'Scraping sensation', 'Sore throat',
    'Spasm', 'Stiffness', 'Stitches', 'Stumbling in throat',
    'Swelling', 'Syphilitic', 'Tension', 'Throat, sensitive',
    'Tickling', 'Tonsils', 'Ulcers', 'Varicose veins', 'Voice',
    'Warmth agg.', 'Weakness', 'Windpipe',
    // ... and 90+ more rubrics
  ],
  'External Throat': [
    'Abscess', 'Coldness', 'Cracked', 'Drawing', 'Dryness', 'Eruptions',
    'Goitre', 'Heat', 'Induration', 'Inflammation', 'Itching', 'Lump',
    'Nodes', 'Pain', 'Perspiration', 'Pulsation', 'Stiffness', 'Stitches',
    'Struma', 'Swelling', 'Tension', 'Tumors', 'Ulcers',
    // ... and 1 more rubric
  ],
  'Stomach': [
    'Appetite increased', 'Appetite decreased', 'Appetite lost', 'Appetite perverted',
    'Aversion to food', 'Belching', 'Bitter taste', 'Bloating', 'Burning',
    'Coldness', 'Cramp', 'Craving', 'Desires', 'Digestion weak', 'Distension',
    'Drinks', 'Dryness', 'Emptiness', 'Eructations', 'Flatulence',
    'Flushing', 'Food lies heavy', 'Fullness', 'Gas', 'Gnawing',
    'Heartburn', 'Heat', 'Heaviness', 'Hiccough', 'Indigestion',
    'Loathing food', 'Moisture', 'Nausea', 'Oppression', 'Pain',
    'Paralysis', 'Pressure', 'Pulsation', 'Qualmish', 'Rising sensation',
    'Salty taste', 'Sinking sensation', 'Smarting', 'Sour taste',
    'Sour eructations', 'Spasms', 'Stitches', 'Stomach, weak',
    'Strangulation', 'Tenderness', 'Thirst', 'Thirstlessness',
    'Throbbing', 'Tightness', 'Trembling', 'Vomiting', 'Waterbrash',
    'Weakness', 'Weight', 'Worms',
    // ... and 80+ more rubrics
  ],
  'Abdomen': [
    'Pain - cramping, griping', 'Pain - cutting', 'Pain - dragging',
    'Pain - drawing', 'Pain - gnawing', 'Pain - lancinating', 'Pain - pressing',
    'Pain - soreness', 'Pain - stitching', 'Pain - tearing', 'Pain - throbbing',
    'Pain - ulcerative', 'Pain - wandering', 'Pain - burning', 'Pain - bursting',
    'Pain - colicky', 'Pain - hypochondrium', 'Pain - umbilical region',
    'Pain - inguinal region', 'Pain - iliac region', 'Pain - hepatic region',
    'Pain - splenic region', 'Pain - hypogastric', 'Pain - general',
    'Bloating / Distension', 'Coldness', 'Colic', 'Constriction',
    'Corrosive sensation', 'Cramps', 'Discoloration', 'Drawing',
    'Emptiness', 'Engorgement', 'Eruptions', 'Flatulence', 'Flatus',
    'Fluctuation', 'Fulness', 'Gases, obstructed', 'Gurgling',
    'Hardness', 'Heat', 'Heaviness', 'Hernia', 'Induration',
    'Inflammation', 'Itching', 'Jerking', 'Knots', 'Movements',
    'Numbness', 'Obstruction', 'Pendulous', 'Perspiration', 'Pulsation',
    'Rolling sensation', 'Rumbling', 'Sensitive to pressure', 'Shooting',
    'Sinking', 'Stiffness', 'Stitches', 'Swelling', 'Tenderness',
    'Tension', 'Throbbing', 'Tightness', 'Tumors', 'Ulcers',
    'Uneasiness', 'Warmth', 'Weakness', 'Worms',
    // ... and 330+ more rubrics
  ],
  'Stool': [
    'Acrid', 'Adhesive', 'Albuminous', 'Anus', 'Aphthous', 'Biting',
    'Black', 'Bloody', 'Borborygmi', 'Burning', 'Clay-colored',
    'Cleansing sensation', 'Clotted', 'Colic before', 'Colicky', 'Constipation',
    'Copious', 'Corrosive', 'Cramp', 'Cutting', 'Dark', 'Day', 'Diarrhea',
    'Difficult', 'Discharge', 'Dysentery', 'Ejection', 'Expulsive force',
    'Fatty', 'Fetid', 'Flaky', 'Flatulence', 'Fluid', 'Food particles',
    'Formication', 'Foul', 'Frequent', 'Fruits', 'Gelatinous',
    'Glaire', 'Glowing', 'Gnawing', 'Gushing', 'Hard', 'Heat after',
    'Herpes', 'Incomplete', 'Indifferent to stool', 'Ineffective urging',
    'Involuntary', 'Irritation', 'Itching', 'Jelly-like', 'Labor-like pain',
    'Large', 'Leaving sensation', 'Loose', 'Lumbrici', 'Lumpy',
    'Maggots', 'Mucus', 'Mucous', 'Murky', 'Morning', 'Narrow',
    'Night', 'Noisy', 'Obstructed', 'Offensive', 'Painful', 'Pale',
    'Pappy', 'Paralysis', 'Particles', 'Passing', 'Pasty', 'Peculiar smell',
    'Piles', 'Pitchy', 'Profuse', 'Prolapse', 'Pulsation', 'Pus',
    'Putrid', 'Quinsy', 'Rectum', 'Red', 'Ribbon-like', 'Rumbling',
    'Sanious', 'Scanty', 'Schirrus', 'Slippery', 'Small', 'Smarting',
    'Smell', 'Sour', 'Sphincter', 'Spurious', 'Squirting', 'Staining',
    'Stitching', 'Stools', 'Straining', 'Stringy', 'Stubs', 'Subsultus',
    'Sudden', 'Sugar', 'Suppuration', 'Sweat after', 'Tar-like', 'Tenacious',
    'Tenesmus', 'Thin', 'Thirst after', 'Throbbing', 'Tough', 'Undigested',
    'Urging', 'Varicose veins', 'Watery', 'Weakness', 'White', 'Worms',
    'Yellow',
    // ... and 360+ more rubrics
  ],
  'Urine': [
    'Acrid', 'Albuminous', 'Bed-wetting', 'Black', 'Bloody', 'Burning',
    'Clear', 'Cloudy', 'Color', 'Copious', 'Corrosive', 'Cutting',
    'Dark', 'Decomposition', 'Deposit', 'Diabetes', 'Difficult',
    'Diminished', 'Discharge', 'Fishy odor', 'Flaky', 'Flow',
    'Frequent', 'Gleet', 'Gritty', 'Gushing', 'Holding', 'Hot',
    'Incontinence', 'Involuntary', 'Jelly-like', 'Milky', 'Muddy',
    'Musty odor', 'Night', 'Nocturnal', 'Offensive', 'Pale', 'Painful',
    'Passed', 'Pus', 'Red', 'Scanty', 'Sediment', 'Sharp',
    'Slow', 'Smoky', 'Spasmodic', 'Staining', 'Strangury', 'Sugar',
    'Suppressed', 'Thick', 'Turbid', 'Urging', 'Viscid', 'Watery',
    'Weakness', 'Yellow',
    // ... and 0 more rubrics
  ],
  'Kidney': [
    'Affection of', 'Area', 'Catarrh', 'Colic', 'Congestion', 'Cutting',
    'Disease', 'Dragging', 'Enlargement', 'Gravel', 'Heat', 'Heaviness',
    'Inflammation', 'Itching', 'Lancinating', 'Looseness', 'Movement',
    'Nephritis', 'Pain', 'Palpation', 'Paralysis', 'Perspiration',
    'Pressure', 'Pulsation', 'Region of', 'Renal', 'Sensitiveness',
    'Sinking', 'Smarting', 'Soreness', 'Spasm', 'Stiffness',
    'Stitching', 'Stone', 'Suppuration', 'Swelling', 'Tenderness',
    'Throbbing', 'Tumultuous', 'Uneasiness', 'Weakness', 'Weight',
    // ... and 20+ more rubrics
  ],
  'Male Genitalia': [
    'Attraction', 'Coldness', 'Cramps', 'Cutting', 'Desire increased',
    'Desire diminished', 'Desire lost', 'Drawing', 'Emission', 'Eruptions',
    'Excitement', 'Flaccidity', 'Gleet', 'Gnawing', 'Gonorrhoea',
    'Heat', 'Heaviness', 'Herpes', 'Hydrocele', 'Impotence',
    'Induration', 'Inflammation', 'Itching', 'Jerking', 'Lancinating',
    'Moisture', 'Numbness', 'Odor', 'Orchitis', 'Pain',
    'Paralysis', 'Perspiration', 'Pinching', 'Pressing', 'Prostate',
    'Pulsation', 'Seminal', 'Shooting', 'Soreness', 'Stiffness',
    'Stitching', 'Stings', 'Suppuration', 'Sweat', 'Swelling',
    'Tension', 'Testes', 'Testicles', 'Throbbing', 'Tumors',
    'Ulcers', 'Varicocele', 'Weakness', 'Warts', 'Wet dreams',
    // ... and 20+ more rubrics
  ],
  'Urethra': [
    'Biting', 'Bleeding', 'Boring', 'Burning', 'Chapped', 'Coldness',
    'Constriction', 'Corrosive', 'Cramp', 'Cutting', 'Discharge',
    'Drawing', 'Eruptions', 'Excrescences', 'Flow', 'Formication',
    'Gleet', 'Gnawing', 'Heat', 'Inflammation', 'Itching',
    'Jerking', 'Lancinating', 'Moisture', 'Mucus', 'Narrow',
    'Noise in', 'Obstruction', 'Pain', 'Paralysis', 'Piercing',
    'Pimples', 'Pressing', 'Prickling', 'Prostatitis', 'Pulsation',
    'Shooting', 'Smarting', 'Soreness', 'Spasmodic', 'Stiffness',
    'Sticking', 'Stinging', 'Stone', 'Stricture', 'Stitching',
    'Suppuration', 'Swelling', 'Tearing', 'Tenesmus', 'Throbbing',
    'Tickling', 'Tumors', 'Ulcers', 'Varices', 'Weakness',
    'Warts', 'Wetting', 'Wriggling',
    // ... and 120+ more rubrics
  ],
  'Female Genitalia': [
    'Abortion tendency', 'Amenorrhoea', 'Breasts', 'Chafing', 'Clitoris',
    'Colic', 'Conception', 'Corrosive', 'Cutting', 'Discharge',
    'Dysmenorrhoea', 'Eruptions', 'Excitement', 'Flatus', 'Frigidity',
    'Genitalia', 'Heat', 'Herpes', 'Hysteria', 'Itching',
    'Leucorrhoea', 'Lochia', 'Lumbar pain', 'Mammae', 'Menses',
    'Menopause', 'Nipples', 'Ovaries', 'Ovulation', 'Pain',
    'Paralysis', 'Pregnancy', 'Pruritus', 'Prolapse', 'Pulsation',
    'Sexual desire', 'Sterility', 'Stiffness', 'Stitching', 'Suppuration',
    'Swelling', 'Tenderness', 'Tension', 'Throbbing', 'Tumors',
    'Ulcers', 'Uterus', 'Vagina', 'Weakness', 'Warts',
    // ... and 200+ more rubrics
  ],
};

// Keep original compact categories for backward compatibility
export const CHAPTER_CATEGORIES: Record<string, string[]> = {
  'Mind': ['Irritability', 'Anxiety', 'Fear', 'Grief', 'Anger', 'Depression', 'Weeping', 'Loquacity', 'Rapid speech', 'Dullness', 'Memory weakness', 'Timidity', 'Suspiciousness', 'Restlessness', 'Aversion to company', 'Desires to be alone', 'Helplessness', 'Hope', 'Indifference', 'Jealousy', 'Mirth', 'Sentimental'],
  'Head': ['Pain - general', 'Pain - temporal', 'Pain - frontal', 'Pain - occipital', 'Pain - vertex', 'Pain - throbbing', 'Pain - pressing', 'Pain - bursting', 'Pain - boring', 'Pain - stitching', 'Pain - splitting', 'Pain - < sun', 'Pain - < noise', 'Pain - < movement', 'Congestion', 'Heaviness', 'Vertigo'],
  'Eye': ['Pain', 'Burning', 'Watering', 'Redness', 'Itching', 'Dim vision', 'Photophobia', 'Lachrymation', 'Dryness', 'Swelling', 'Styes', 'Ulceration', 'Cataract'],
  'Ear': ['Pain', 'Discharge', 'Ringing/Tinnitus', 'Hearing - acute', 'Hearing - diminished', 'Itching', 'Swelling', 'Hardness of hearing'],
  'Nose': ['Coryza', 'Discharge - watery', 'Discharge - thick', 'Sneezing', 'Obstruction', 'Bleeding/Epistaxis', 'Smell - acute', 'Smell - lost', 'Dryness', 'Itching'],
  'Stomach': ['Nausea', 'Vomiting', 'Heartburn', 'Appetite - increased', 'Appetite - decreased', 'Appetite - lost', 'Thirst', 'Craving', 'Aversion', 'Indigestion', 'Eructations', 'Fullness', 'Pain', 'Sour taste'],
  'Abdomen': ['Pain - general', 'Pain - umbilical', 'Pain - hypogastric', 'Pain - hepatic', 'Pain - splenic', 'Bloating/Distension', 'Flatulence', 'Hardness', 'Tenderness', 'Gurgling'],
  'Skin': ['Itching', 'Burning', 'Dry', 'Eruptions', 'Urticaria', 'Eczema', 'Psoriasis', 'Warts', 'Ulcers', 'Perspiration'],
  'Extremities': ['Pain - joints', 'Pain - limbs', 'Weakness', 'Trembling', 'Cramps', 'Stiffness', 'Swelling', 'Numbness', 'Coldness', 'Restlessness'],
  'Respiratory': ['Difficulty breathing', 'Asthma', 'Wheezing', 'Cough - dry', 'Cough - productive', 'Expectoration', 'Suffocation', 'Chest tightness'],
  'Sleep': ['Sleeplessness', 'Sleepy', 'Disturbed', 'Awakens early', 'Sleep position', 'Dreams', 'Snoring', 'Sleep walking'],
  'Chills': ['Chilly', 'Shivering', 'Chills - periodic', 'Chills - from draft', 'Chills - after drinking'],
  'Fever': ['High fever', 'Low fever', 'Intermittent', 'Remittent', 'Morning fever', 'Evening fever', 'Night fever', 'Sweat with fever', 'Thirst during fever'],
  'Perspiration': ['Profuse', 'Scanty', 'Offensive', 'Sour', 'Cold', 'Hot', 'Night sweats', 'Under arms', 'On palms', 'On soles'],
  'Generalities': ['Aggravation', 'Amelioration', 'Constitution', 'Sides', 'Weather', 'Time', 'Motion', 'Rest', 'Position'],
  'Female Genitalia': ['Menses - profuse', 'Menses - scanty', 'Menses - irregular', 'Menses - painful', 'Menses - early', 'Menses - late', 'Leucorrhea', 'Pain - ovarian', 'Pain - uterine', 'Menopause'],
  'Male Genitalia': ['Pain', 'Weakness', 'Emissions', 'Desire - increased', 'Desire - decreased', 'Swelling', 'Induration'],
  'Throat': ['Pain', 'Dryness', 'Swelling', 'Difficulty swallowing', 'Tonsillitis', 'Foreign body sensation', 'Burning', 'Redness'],
  'Chest': ['Pain', 'Tightness', 'Congestion', 'Palpitation', 'Oppression', 'Weakness'],
  'Back': ['Pain - cervical', 'Pain - dorsal', 'Pain - lumbar', 'Pain - sacral', 'Stiffness', 'Weakness'],
};

export const REPERTORY_DATA: RubricData[] = [
  {
    id: 'mind-irritability',
    chapter: 'Mind',
    rubrics: [
      { id: 'mind-1', text: 'Irritability', chapter: 'Mind', remedies: [{ name: 'Nux Vomica', grade: 3 }, { name: 'Chamomilla', grade: 3 }, { name: 'Staphysagria', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Lycopodium', grade: 3 }] },
      { id: 'mind-2', text: 'Irritability - with headache', chapter: 'Mind', remedies: [{ name: 'Nux Vomica', grade: 2 }, { name: 'Bryonia', grade: 2 }] },
      { id: 'mind-3', text: 'Anxiety', chapter: 'Mind', remedies: [{ name: 'Aconite', grade: 3 }, { name: 'Argentum Nitricum', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Gelsemium', grade: 3 }, { name: 'Ignatia', grade: 3 }, { name: 'Kali Arsenicosum', grade: 3 }, { name: 'Phosphorus', grade: 3 }] },
      { id: 'mind-4', text: 'Anxiety - with palpitations', chapter: 'Mind', remedies: [{ name: 'Aconite', grade: 2 }, { name: 'Argentum Nitricum', grade: 2 }, { name: 'Arsenicum Album', grade: 2 }, { name: 'Phosphorus', grade: 2 }] },
      { id: 'mind-5', text: 'Fear - of death', chapter: 'Mind', remedies: [{ name: 'Aconite', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Lachesis', grade: 3 }] },
      { id: 'mind-6', text: 'Fear - of death - predicts time', chapter: 'Mind', remedies: [{ name: 'Aconite', grade: 2 }, { name: 'Arsenicum Album', grade: 2 }] },
      { id: 'mind-7', text: 'Grief - silent', chapter: 'Mind', remedies: [{ name: 'Natrum Mur', grade: 3 }, { name: 'Ignatia', grade: 3 }, { name: 'Phosphoric Acid', grade: 3 }, { name: 'Sepia', grade: 3 }] },
      { id: 'mind-8', text: 'Depression', chapter: 'Mind', remedies: [{ name: 'Aurum', grade: 3 }, { name: 'Ignatia', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Sepia', grade: 3 }] },
      { id: 'mind-9', text: 'Weeping', chapter: 'Mind', remedies: [{ name: 'Pulsatilla', grade: 3 }, { name: 'Ignatia', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Sepia', grade: 3 }, { name: 'Aconite', grade: 3 }] },
      { id: 'mind-10', text: 'Restlessness', chapter: 'Mind', remedies: [{ name: 'Arsenicum Album', grade: 3 }, { name: 'Rhus Tox', grade: 3 }, { name: 'Aconite', grade: 3 }, { name: 'Zincum', grade: 3 }] },
      { id: 'mind-11', text: 'Anger - violent', chapter: 'Mind', remedies: [{ name: 'Nux Vomica', grade: 3 }, { name: 'Chamomilla', grade: 3 }, { name: 'Staphysagria', grade: 3 }, { name: 'Belladonna', grade: 3 }] },
      { id: 'mind-12', text: 'Memory - weakness of', chapter: 'Mind', remedies: [{ name: 'Baryta Carb', grade: 2 }, { name: 'Lycopodium', grade: 2 }, { name: 'Silicea', grade: 2 }, { name: 'Syphilinum', grade: 2 }] },
    ],
  },
  {
    id: 'head-pain',
    chapter: 'Head',
    rubrics: [
      { id: 'head-1', text: 'Headache - throbbing', chapter: 'Head', remedies: [{ name: 'Belladonna', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Sanguinaria', grade: 3 }, { name: 'Glonoine', grade: 3 }, { name: 'Nux Vomica', grade: 3 }] },
      { id: 'head-2', text: 'Headache - bursting', chapter: 'Head', remedies: [{ name: 'Belladonna', grade: 2 }, { name: 'Natrum Mur', grade: 2 }, { name: 'Nux Vomica', grade: 2 }, { name: 'Lycopodium', grade: 2 }] },
      { id: 'head-3', text: 'Headache - frontal', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Nux Vomica', grade: 3 }, { name: 'Sanguinaria', grade: 3 }, { name: 'Spigelia', grade: 3 }] },
      { id: 'head-4', text: 'Headache - temporal', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 2 }, { name: 'Crocus Sativus', grade: 2 }, { name: 'Lachesis', grade: 2 }, { name: 'Sanguinaria', grade: 2 }] },
      { id: 'head-5', text: 'Headache - occipital', chapter: 'Head', remedies: [{ name: 'Silicea', grade: 2 }, { name: 'Lycopodium', grade: 2 }, { name: 'Sepia', grade: 2 }, { name: 'Cimicifuga', grade: 2 }] },
      { id: 'head-6', text: 'Headache - vertex', chapter: 'Head', remedies: [{ name: 'Bryonia', grade: 2 }, { name: 'China', grade: 2 }, { name: 'Thuja', grade: 2 }, { name: 'Natrum Mur', grade: 2 }] },
      { id: 'head-7', text: 'Headache - < sun', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 3 }, { name: 'Belladonna', grade: 3 }, { name: 'Lachesis', grade: 3 }, { name: 'Carcinosinum', grade: 3 }] },
      { id: 'head-8', text: 'Headache - < noise', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 2 }, { name: 'Nux Vomica', grade: 2 }, { name: 'Bryonia', grade: 2 }, { name: 'Belladonna', grade: 2 }] },
      { id: 'head-9', text: 'Headache - < movement', chapter: 'Head', remedies: [{ name: 'Bryonia', grade: 2 }, { name: 'Belladonna', grade: 2 }] },
      { id: 'head-10', text: 'Headache - > sleep', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 2 }, { name: 'Nux Vomica', grade: 2 }, { name: 'Sepia', grade: 2 }] },
      { id: 'head-11', text: 'Headache - with nausea', chapter: 'Head', remedies: [{ name: 'Iris Versicolor', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Nux Vomica', grade: 3 }, { name: 'Sanguinaria', grade: 3 }, { name: 'Cyclamen', grade: 3 }] },
      { id: 'head-12', text: 'Headache - with vomiting', chapter: 'Head', remedies: [{ name: 'Iris Versicolor', grade: 2 }, { name: 'Sanguinaria', grade: 2 }, { name: 'Cyclamen', grade: 2 }, { name: 'Ipecac', grade: 2 }] },
      { id: 'head-13', text: 'Headache - migraine', chapter: 'Head', remedies: [{ name: 'Natrum Mur', grade: 3 }, { name: 'Sanguinaria', grade: 3 }, { name: 'Iris Versicolor', grade: 3 }, { name: 'Crocus Sativus', grade: 3 }, { name: 'Spigelia', grade: 3 }, { name: 'Sepia', grade: 3 }] },
    ],
  },
  {
    id: 'stomach-nausea',
    chapter: 'Stomach',
    rubrics: [
      { id: 'stom-1', text: 'Nausea', chapter: 'Stomach', remedies: [{ name: 'Ipecac', grade: 3 }, { name: 'Nux Vomica', grade: 3 }, { name: 'Antim Crud', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Sepia', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }] },
      { id: 'stom-2', text: 'Nausea - with headache', chapter: 'Stomach', remedies: [{ name: 'Iris Versicolor', grade: 2 }, { name: 'Sanguinaria', grade: 2 }, { name: 'Cyclamen', grade: 2 }, { name: 'Natrum Mur', grade: 2 }, { name: 'Nux Vomica', grade: 2 }] },
      { id: 'stom-3', text: 'Vomiting', chapter: 'Stomach', remedies: [{ name: 'Ipecac', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Zincum', grade: 3 }, { name: 'Cocculus', grade: 3 }] },
      { id: 'stom-4', text: 'Heartburn', chapter: 'Stomach', remedies: [{ name: 'Robinia', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Carbo Veg', grade: 3 }, { name: 'Nux Vomica', grade: 3 }, { name: 'Pulsatilla', grade: 3 }] },
      { id: 'stom-5', text: 'Appetite - increased', chapter: 'Stomach', remedies: [{ name: 'Iodum', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Lycopodium', grade: 3 }, { name: 'Chelidonium', grade: 3 }, { name: 'China', grade: 3 }, { name: 'Sulphur', grade: 3 }, { name: 'Tuberculinum', grade: 3 }] },
      { id: 'stom-6', text: 'Appetite - decreased', chapter: 'Stomach', remedies: [{ name: 'Nux Vomica', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Carbo Veg', grade: 3 }, { name: 'Lycopodium', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Sepia', grade: 3 }] },
      { id: 'stom-7', text: 'Thirst - increased', chapter: 'Stomach', remedies: [{ name: 'Arsenicum Album', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Lycopodium', grade: 3 }, { name: 'Natrum Mur', grade: 3 }, { name: 'Sulphur', grade: 3 }, { name: 'Tuberculinum', grade: 3 }] },
      { id: 'stom-8', text: 'Thirst - thirstless', chapter: 'Stomach', remedies: [{ name: 'Pulsatilla', grade: 3 }, { name: 'Antim Crud', grade: 3 }, { name: 'Apis', grade: 3 }, { name: 'Calcarea Carb', grade: 3 }, { name: 'Gelsemium', grade: 3 }] },
      { id: 'stom-9', text: 'Desires - sour things', chapter: 'Stomach', remedies: [{ name: 'Antim Crud', grade: 2 }, { name: 'Tuberculinum', grade: 2 }, { name: 'Hepar Sulph', grade: 2 }, { name: 'Sepia', grade: 2 }, { name: 'Argentum Nitricum', grade: 2 }] },
      { id: 'stom-10', text: 'Desires - sweets', chapter: 'Stomach', remedies: [{ name: 'Argentum Nitricum', grade: 3 }, { name: 'Calcare Carb', grade: 3 }, { name: 'Lycopodium', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Sulphur', grade: 3 }, { name: 'Tuberculinum', grade: 3 }] },
      { id: 'stom-11', text: 'Desires - spicy food', chapter: 'Stomach', remedies: [{ name: 'Nux Vomica', grade: 2 }, { name: 'Phosphorus', grade: 2 }, { name: 'Sulphur', grade: 2 }] },
      { id: 'stom-12', text: 'Aversions - fats', chapter: 'Stomach', remedies: [{ name: 'Pulsatilla', grade: 2 }, { name: 'Carbo Veg', grade: 2 }, { name: 'Antim Crud', grade: 2 }, { name: 'Calcarea Carb', grade: 2 }, { name: 'Sepia', grade: 2 }] },
    ],
  },
  {
    id: 'extremities-joints',
    chapter: 'Extremities',
    rubrics: [
      { id: 'ext-1', text: 'Pain - joints', chapter: 'Extremities', remedies: [{ name: 'Bryonia', grade: 3 }, { name: 'Rhus Tox', grade: 3 }, { name: 'Arnica', grade: 3 }, { name: 'Bellis Perennis', grade: 3 }, { name: 'Ledum', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Ruta', grade: 3 }, { name: 'Sulphur', grade: 3 }] },
      { id: 'ext-2', text: 'Pain - joints - < movement', chapter: 'Extremities', remedies: [{ name: 'Bryonia', grade: 3 }] },
      { id: 'ext-3', text: 'Pain - joints - > movement', chapter: 'Extremities', remedies: [{ name: 'Rhus Tox', grade: 3 }, { name: 'Ferrum Phos', grade: 3 }] },
      { id: 'ext-4', text: 'Stiffness', chapter: 'Extremities', remedies: [{ name: 'Rhus Tox', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Arnica', grade: 3 }, { name: 'Cimicifuga', grade: 3 }, { name: 'Sanguinaria', grade: 3 }, { name: 'Sulphur', grade: 3 }] },
      { id: 'ext-5', text: 'Weakness', chapter: 'Extremities', remedies: [{ name: 'Gelsemium', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Cocculus', grade: 3 }, { name: 'Sepia', grade: 3 }, { name: 'Causticum', grade: 3 }] },
      { id: 'ext-6', text: 'Cramps', chapter: 'Extremities', remedies: [{ name: 'Cuprum Met', grade: 2 }, { name: 'Cicuta', grade: 2 }, { name: 'Magnesia Phos', grade: 2 }, { name: 'Nux Vomica', grade: 2 }, { name: 'Secale', grade: 2 }] },
      { id: 'ext-7', text: 'Trembling', chapter: 'Extremities', remedies: [{ name: 'Agaricus', grade: 2 }, { name: 'Gelsemium', grade: 2 }, { name: 'Zincum', grade: 2 }, { name: 'Phosphorus', grade: 2 }, { name: 'Silicea', grade: 2 }, { name: 'Thuja', grade: 2 }] },
      { id: 'ext-8', text: 'Swelling - joints', chapter: 'Extremities', remedies: [{ name: 'Apis', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Ledum', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Rhus Tox', grade: 3 }, { name: 'Ruta', grade: 3 }, { name: 'Sulphur', grade: 3 }] },
    ],
  },
  {
    id: 'sleep-dreams',
    chapter: 'Sleep',
    rubrics: [
      { id: 'sleep-1', text: 'Sleeplessness', chapter: 'Sleep', remedies: [{ name: 'Coffea', grade: 3 }, { name: 'Nux Vomica', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }, { name: 'Aconite', grade: 3 }, { name: 'Lachesis', grade: 3 }, { name: 'Sulphur', grade: 3 }, { name: 'Zincum', grade: 3 }, { name: 'Opium', grade: 3 }, { name: 'Passiflora', grade: 3 }] },
      { id: 'sleep-2', text: 'Sleeplessness - from thoughts', chapter: 'Sleep', remedies: [{ name: 'Coffea', grade: 2 }, { name: 'Nux Vomica', grade: 2 }, { name: 'Ignatia', grade: 2 }, { name: 'Thuja', grade: 2 }] },
      { id: 'sleep-3', text: 'Sleeplessness - after midnight', chapter: 'Sleep', remedies: [{ name: 'Lachesis', grade: 3 }, { name: 'Sulphur', grade: 3 }, { name: 'Medorrhinum', grade: 3 }, { name: 'Syphilinum', grade: 3 }, { name: 'Arsenicum Album', grade: 3 }] },
      { id: 'sleep-4', text: 'Sleepiness', chapter: 'Sleep', remedies: [{ name: 'Nux Moschata', grade: 2 }, { name: 'Opium', grade: 2 }, { name: 'Phosphorus', grade: 2 }, { name: 'Sulphur', grade: 2 }, { name: 'Antim Crud', grade: 2 }, { name: 'Gelsemium', grade: 2 }] },
      { id: 'sleep-5', text: 'Dreams - anxious', chapter: 'Sleep', remedies: [{ name: 'Aconite', grade: 2 }, { name: 'Arsenicum Album', grade: 2 }, { name: 'Ignatia', grade: 2 }, { name: 'Kali Phos', grade: 2 }, { name: 'Phosphorus', grade: 2 }, { name: 'Thuja', grade: 2 }] },
      { id: 'sleep-6', text: 'Dreams - vivid', chapter: 'Sleep', remedies: [{ name: 'Lachesis', grade: 2 }, { name: 'Cannabis Indica', grade: 2 }, { name: 'Thuja', grade: 2 }, { name: 'Nitric Acid', grade: 2 }, { name: 'Phosphorus', grade: 2 }] },
    ],
  },
  {
    id: 'respiratory-cough',
    chapter: 'Respiratory',
    rubrics: [
      { id: 'resp-1', text: 'Cough - dry', chapter: 'Respiratory', remedies: [{ name: 'Belladonna', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Drosera', grade: 3 }, { name: 'Spongia', grade: 3 }, { name: 'Coccus Cacti', grade: 3 }, { name: 'Rumex', grade: 3 }, { name: 'Aconite', grade: 3 }] },
      { id: 'resp-2', text: 'Cough - loose', chapter: 'Respiratory', remedies: [{ name: 'Antim Tart', grade: 3 }, { name: 'Bryonia', grade: 3 }, { name: 'Ipecac', grade: 3 }, { name: 'Kali Bich', grade: 3 }, { name: 'Pulsatilla', grade: 3 }, { name: 'Sepia', grade: 3 }, { name: 'Stannum', grade: 3 }] },
      { id: 'resp-3', text: 'Cough - > eating', chapter: 'Respiratory', remedies: [{ name: 'Chelidonium', grade: 2 }, { name: 'Natrum Sulph', grade: 2 }] },
      { id: 'resp-4', text: 'Difficult breathing', chapter: 'Respiratory', remedies: [{ name: 'Arsenicum Album', grade: 3 }, { name: 'Antim Tart', grade: 3 }, { name: 'Ipecac', grade: 3 }, { name: 'Lachesis', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Spongia', grade: 3 }] },
      { id: 'resp-5', text: 'Wheezing', chapter: 'Respiratory', remedies: [{ name: 'Arsenicum Album', grade: 2 }, { name: 'Ipecac', grade: 2 }, { name: 'Spongia', grade: 2 }, { name: 'Antim Tart', grade: 2 }, { name: 'Natrum Sulph', grade: 2 }] },
      { id: 'resp-6', text: 'Cough - < night', chapter: 'Respiratory', remedies: [{ name: 'Arsenicum Album', grade: 3 }, { name: 'Drosera', grade: 3 }, { name: 'Phosphorus', grade: 3 }, { name: 'Spongia', grade: 3 }, { name: 'Rumex', grade: 3 }] },
    ],
  },
];
