export interface Remedy {
  name: string;
  abbrev?: string;
  kingdom?: string;
  family?: string;
  temperament?: string;
  thermal?: string;
  thirst?: string;
  desires?: string[];
  aversions?: string[];
  modalities?: { better?: string[]; worse?: string[] };
  keynotes?: string[];
  mind?: string[];
  physical?: string[];
  clinical?: string[];
  relations?: { antidotes?: string[]; complementary?: string[]; followedWellBy?: string[]; inimical?: string[]; compatible?: string[] };
}

export const MATERIA_MEDICA_DATA: Remedy[] = [
  {
    name: 'Nux Vomica',
    abbrev: 'Nux-v',
    kingdom: 'Plant',
    family: 'Loganiaceae',
    temperament: 'Irritable, impatient, ambitious, perfectionist',
    thermal: 'Chilly',
    thirst: 'Increased - for large quantities',
    desires: ['Fats', 'Spicy food', 'Coffee', 'Alcohol', 'Stimulants'],
    aversions: ['Tobacco', 'Sweets', 'Fat'],
    modalities: { better: ['Rest', 'Sleep', 'Quiet', 'Uncovering'], worse: ['Morning', 'Noise', 'Cold air', 'Stooping', 'After eating', 'Mental exertion'] },
    keynotes: ['Great irritability', 'Nausea with effort', 'Desires stimulants', 'Constipation - ineffectual urging', 'Headache from overindulgence'],
    mind: ['Very irritable and impatient', 'Angry when contradicted', 'Fault-finding', 'Cannot bear noise, odors, light', 'Suicidal disposition but lacks courage', 'Desires everything and nothing satisfies', 'Dictatorial and domineering', 'Over-sensitive to external impressions'],
    physical: ['Headache - frontal, splitting', 'Stomach - nausea, sour taste, heartburn', 'Constipation with frequent ineffectual urging', 'Back pain - lumbar region', 'Hangover remedy', 'Insomnia from mental strain'],
    clinical: ['Hangover', 'Constipation', 'Gastritis', 'GERD', 'Irritable Bowel Syndrome', 'Headache from stress', 'Insomnia', 'Hemorrhoids'],
    relations: { antidotes: ['Coffea', 'Ignatia', 'Pulsatilla', 'Zincum'], complementary: ['Sulphur', 'Lycopodium'], followedWellBy: ['Sulphur', 'Phosphorus'], inimical: ['Zincum'] },
  },
  {
    name: 'Pulsatilla',
    abbrev: 'Puls',
    kingdom: 'Plant',
    family: 'Ranunculaceae',
    temperament: 'Gentle, mild, yielding, emotional, weepy',
    thermal: 'Chilly but desires open air',
    thirst: 'Thirstless',
    desires: ['Sweets', 'Rich food', 'Ice cream', 'Fatty food'],
    aversions: ['Hot food', 'Fat', 'Warm drinks'],
    modalities: { better: ['Open air', 'Cold applications', 'Gentle motion', 'Crying', 'Sympathy'], worse: ['Heat', 'Warm room', 'Rich food', 'Fats', 'Evening', 'After eating', 'Lying on left side'] },
    keynotes: ['Changeable symptoms', 'Weeping', 'Thirstless', 'Desires open air', 'Aggravation from heat', 'Mild and gentle disposition', 'Discharges thick, bland, yellowish-green'],
    mind: ['Weeps easily', 'Changeable mood', 'Gentle, mild, yielding', 'Easily offended', 'Desires sympathy and company', 'Cannot bear contradiction', 'Fears the dark, ghosts, being alone', 'Depression after grief', 'Jealousy'],
    physical: ['Coryza with thick yellow discharge', 'Cough dry at night, loose in morning', 'Menses - changeable, late, scanty', 'Digestive issues from rich food', 'Joint pains shifting', 'Styes'],
    clinical: ['Colds', 'Cough', 'Menstrual problems', 'Otitis media', 'Conjunctivitis', 'Varicose veins', 'Rheumatism', 'Gastritis'],
    relations: { antidotes: ['Camphora', 'Coffee', 'Nux Vomica', 'Pulsatilla'], complementary: ['Sepia', 'Sulphur'], followedWellBy: ['Sepia', 'Sulphur'], inimical: ['Lycopodium'] },
  },
  {
    name: 'Sulphur',
    abbrev: 'Sulph',
    kingdom: 'Mineral',
    family: 'Element',
    temperament: 'Philosophical, intellectual, lazy, selfish',
    thermal: 'Hot patient - burning sensation',
    thirst: 'Increased',
    desires: ['Sweets', 'Sour', 'Spicy', 'Alcohol', 'Fats'],
    aversions: ['Eggs', 'Milk', 'Sweets (sometimes)'],
    modalities: { better: ['Warm dry weather', 'Standing', 'Tying head tightly'], worse: ['Heat of bed', 'Bathing', 'Standing', '11 AM', 'At seashore', 'Left side', 'Tight clothing'] },
    keynotes: ['Burning sensation', 'Hot patient', 'Standing is a disagreeable position', 'Dirty, untidy', 'Philosophical', 'Redness of orifices', 'Relapses', 'Desires sweets'],
    mind: ['Philosophical', 'Intellectual but lazy', 'Egotistical', 'Dreams of great deeds', 'Children - hate to be washed', 'Selfish', 'Aversion to business', 'Wandering thoughts', 'Poor memory'],
    physical: ['Skin - dry, rough, unhealthy, itching, burning', 'Heat - burning in soles, palms, vertex', 'Diarrhea - early morning (5 AM)', 'Constipation - ineffectual urging', 'Prostatitis', 'Rhinitis'],
    clinical: ['Eczema', 'Psoriasis', 'Acne', 'Diarrhea', 'Constipation', 'Otitis media', 'Conjunctivitis', 'Bronchitis', 'Prostatitis', 'Skin diseases'],
    relations: { antidotes: ['Camphora', 'Nux Vomica', 'Pulsatilla'], complementary: ['Lycopodium', 'Calcarea Carb', 'Sepia'], followedWellBy: ['Lycopodium', 'Calcarea Carb'], inimical: ['Lachesis'] },
  },
  {
    name: 'Lycopodium',
    abbrev: 'Lyc',
    kingdom: 'Plant',
    family: 'Lycopodiaceae',
    temperament: 'Intelligent but lacking confidence, fearful, dominant at home',
    thermal: 'Chilly',
    thirst: 'Increased',
    desires: ['Sweets', 'Hot drinks', 'Warm food', 'Oysters'],
    aversions: ['Oysters (sometimes)', 'Cold food'],
    modalities: { better: ['Warm food/drink', 'Warm applications', 'Loose clothing', 'After midnight'], worse: ['4-8 PM', 'Heat of bed', 'Cold air', 'Right side', 'Tight clothing', 'Pressure'] },
    keynotes: ['Lack of self-confidence', 'Right-sided remedy', 'Worse 4-8 PM', 'Gas and bloating', 'Desires sweets', 'Fear of failure in business', 'High abdomen'],
    mind: ['Lack of self-confidence', 'Fear of being alone', 'Fear of failure', 'Dictatorial at home, timid outside', 'Intellectual', 'Avarice', 'Anticipatory anxiety', 'Haughty when sick', 'Weeps when thanked'],
    physical: ['Right-sided complaints', 'Digestive - gas, bloating, heartburn', 'Headache - right temporal', 'Urine - red sand in urine', 'Respiratory - worse cold air', 'Extremities - cracking joints', 'Prostatitis'],
    clinical: ['Gastritis', 'GERD', 'Prostatitis', 'Renal colic', 'UTI', 'Right-sided otitis', 'Eczema', 'Urticaria', 'Bronchitis', 'Constipation'],
    relations: { antidotes: ['Camphora', 'Nux Vomica', 'Pulsatilla'], complementary: ['Sulphur', 'Calcarea Carb', 'Natrum Mur'], followedWellBy: ['Sulphur', 'Calcarea Carb'], inimical: ['Causticum'] },
  },
  {
    name: 'Arsenicum Album',
    abbrev: 'Ars',
    kingdom: 'Mineral',
    family: 'Element',
    temperament: 'Fastidious, anxious, restless, perfectionist',
    thermal: 'Chilly - burning pains relieved by heat',
    thirst: 'Increased - for small sips at frequent intervals',
    desires: ['Warm drinks', 'Sour things', 'Cold water'],
    aversions: ['Water (sometimes)', 'Meat'],
    modalities: { better: ['Heat', 'Warm applications', 'Hot drinks', 'Sitting erect', 'Wrapping up warmly'], worse: ['Cold', 'Midnight to 3 AM', 'After eating', 'Right side', 'Uncovering', 'Sea'] },
    keynotes: ['Restlessness', 'Anxiety', 'Burning pains relieved by heat', 'Thirst for small sips', 'Worse at midnight', 'Fastidious', 'Periodicity'],
    mind: ['Great anxiety and restlessness', 'Fear of death, disease, robbers', 'Desires company', 'Fastidious about order', 'Despair of recovery', 'Does not want to be left alone', 'Perfectionist', 'Miserly'],
    physical: ['Burning pains everywhere', 'Vomiting with burning', 'Diarrhea - burning, offensive', 'Cough - burning, worse midnight', 'Skin - burning, itching', 'Breathlessness', 'Chills'],
    clinical: ['Asthma', 'Food poisoning', 'Cholera', 'Gastroenteritis', 'Pneumonia', 'Anxiety disorders', 'Eczema', 'Fever', 'Cold'],
    relations: { antidotes: ['Nux Vomica', 'Ipecac', 'Phosphorus', 'Sulphur'], complementary: ['Ipecac', 'Phosphorus', 'Sepia'], followedWellBy: ['Phosphorus', 'Sulphur'], inimical: ['Lachesis'] },
  },
  {
    name: 'Bryonia Alba',
    abbrev: 'Bry',
    kingdom: 'Plant',
    family: 'Cucurbitaceae',
    temperament: 'Irritable, anxious about business, wants to be left alone',
    thermal: 'Chilly',
    thirst: 'Increased - for large quantities of cold water',
    desires: ['Warm food', 'Cold drinks'],
    aversions: ['Fat', 'Milk'],
    modalities: { better: ['Rest', 'Pressure', 'Lying on painful side', 'Cold applications', 'Eating'], worse: ['Movement', 'Warmth', 'Morning on waking', 'After eating', 'Touch', 'Right side'] },
    keynotes: ['Worse from movement', 'Better from pressure', 'Thirsty for large quantities', 'Irritable', 'Right-sided remedy', 'Constipation', 'Headache worse from movement'],
    mind: ['Irritable', 'Wants to be left alone', 'Anxious about business', 'Fear of poverty', 'Talks of business', 'Mental dejection', 'Easily angered'],
    physical: ['Headache - bursting, frontal, worse movement', 'Joints - stitching, worse movement', 'Stomach - nausea, vomiting', 'Constipation - hard dry stools', 'Respiratory - dry cough, worse movement', 'Right-sided complaints'],
    clinical: ['Arthritis', 'Pneumonia', 'Pleurisy', 'Gastroenteritis', 'Constipation', 'Headache', 'Cough', 'Bronchitis'],
    relations: { antidotes: ['Camphora', 'Nux Vomica', 'Rhus Tox'], complementary: ['Rhus Tox', 'Alumina'], followedWellBy: ['Rhus Tox', 'Alumina'], inimical: [] },
  },
  {
    name: 'Aconite',
    abbrev: 'Acon',
    kingdom: 'Plant',
    family: 'Ranunculaceae',
    temperament: 'Fearful, anxious, restless, lively',
    thermal: 'Chilly',
    thirst: 'Increased',
    desires: ['Cold water'],
    aversions: [],
    modalities: { better: ['Open air', 'Rest'], worse: ['Cold dry wind', 'Night', 'Lying on affected side', 'Tobacco', 'Noise'] },
    keynotes: ['Sudden onset', 'Fear of death', 'Restlessness', 'Hot and dry skin', 'Pupils constricted', 'Causation - cold dry wind'],
    mind: ['Acute anxiety', 'Fear of death - predicts the hour', 'Restlessness', 'Agitation', 'Fearful', 'Music intolerable', 'Changeable mood', 'Very sensitive to noise'],
    physical: ['Fever - sudden onset, high', 'Pain - intense, acute', 'Tachycardia', 'Pupils constricted', 'Dry cough', 'Skin - hot and dry', 'Thirst for cold water'],
    clinical: ['Fever', 'Panic attacks', 'Colds', 'Cough', 'Croup', 'Conjunctivitis', 'Tinnitus', 'Atrial fibrillation'],
    relations: { antidotes: ['Coffee', 'Nux Vomica', 'Sulphur'], complementary: ['Coffea', 'Sulphur'], followedWellBy: ['Sulphur', 'Belladonna'], inimical: ['Coffee'] },
  },
  {
    name: 'Natrum Muriaticum',
    abbrev: 'Nat-m',
    kingdom: 'Mineral',
    family: 'Element',
    temperament: 'Reserved, responsible, melancholic, duty-bound',
    thermal: 'Chilly',
    thirst: 'Increased',
    desires: ['Salty things', 'Sour things', 'Sweets'],
    aversions: ['Fats', 'Milk', 'Bread'],
    modalities: { better: ['Open air', 'Rest', 'Lying on right side', 'Fasting'], worse: ['Sun', 'Heat', '10 AM', 'Consolation', 'Mental exertion', 'Salt'] },
    keynotes: ['Silent grief', 'Worse from consolation', 'Crazy from grief', 'Craving for salt', 'Headache from sun', 'Dry mucous membranes', 'Tongue mapped/geographic'],
    mind: ['Reserved, introverted', 'Silent grief', 'Does not want consolation', 'Depressed after grief', 'Cannot cry in public', 'Weeps alone', 'Hysterical', 'Dwells on past unpleasant events'],
    physical: ['Headache - throbbing, blinding, worse from sun', 'Coryza - watery like raw white of egg', 'Tongue - mapped/geographic', 'Dry mucous membranes', 'Menstrual - irregular, anemic', 'Eczema - edges of hair'],
    clinical: ['Migraine', 'Depression', 'Alopecia', 'Herpes', 'Eczema', 'Menstrual disorders', 'Colds', 'Anemia', 'Gastritis'],
    relations: { antidotes: ['Ignatia', 'Sepia', 'Aconite'], complementary: ['Ignatia', 'Sepia', 'Phosphorus'], followedWellBy: ['Sepia', 'Phosphorus', 'Ignatia'], inimical: [] },
  },
];
