#!/usr/bin/env python3
"""Step 4: Add EXTREMITIES and GENERALITIES chapters"""

import re

FILE_PATH = '/home/z/my-project/homeodesk-pro/src/kentRepertoryData.ts'

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

content = read_file(FILE_PATH)

# New chapters data
EXTREMITIES = '''{
    id: 'extremities',
    chapter: 'EXTREMITIES',
    rubrics: [
      { id: 'ext-1', text: 'EXTREMITIES - NAILS', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Calc.', 'Carb-v.', 'Caust.', 'Graph.', 'Lyc.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Psor.', 'Rhus-t.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-1', text: 'EXTREMITIES - NAILS - brittle', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Calc.', 'Carb-v.', 'Graph.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-2', text: 'EXTREMITIES - NAILS - cracked', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Calc.', 'Graph.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Pet.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-3', text: 'EXTREMITIES - NAILS - deformed', chapter: 'EXTREMITIES', remedies: ['Ars.', 'Calc.', 'Fluor.', 'Graph.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-4', text: 'EXTREMITIES - NAILS - discolored', chapter: 'EXTREMITIES', remedies: ['Ars.', 'Calc.', 'Carb-v.', 'Graph.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-5', text: 'EXTREMITIES - NAILS - soft', chapter: 'EXTREMITIES', remedies: ['Calc.', 'Carb-v.', 'Graph.', 'Lyc.', 'Nat-m.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-6', text: 'EXTREMITIES - NAILS - splintering', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Calc.', 'Graph.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-7', text: 'EXTREMITIES - NAILS - hangnails', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Calc.', 'Lyc.', 'Med.', 'Nit-ac.', 'Phos.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-8', text: 'EXTREMITIES - NAILS - ingrowing', chapter: 'EXTREMITIES', remedies: ['Calc.', 'Nit-ac.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-9', text: 'EXTREMITIES - NAILS - fungi under', chapter: 'EXTREMITIES', remedies: ['Ars.', 'Calc.', 'Carb-v.', 'Graph.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Psor.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-1-10', text: 'EXTREMITIES - NAILS - felon at roots of', chapter: 'EXTREMITIES', remedies: ['Apis.', 'Ars.', 'Bell.', 'Calc.', 'Carb-ac.', 'Hep.', 'Lach.', 'Merc.', 'Nit-ac.', 'Sil.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2', text: 'EXTREMITIES - UPPER LIMBS', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Anthr.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Calen.', 'Camph.', 'Canth.', 'Carb-an.', 'Carb-v.', 'Caries', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Chin-s.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Crot-h.', 'Cupr.', 'Dros.', 'Equis.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Jug-r.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Par.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plat.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Senec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syz.', 'Tab.', 'Thuj.', 'Valer.', 'Verb.', 'Viol-t.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-1', text: 'EXTREMITIES - UPPER LIMBS - Shoulder', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Camph.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-1', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - pain in', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-2', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - pain - rheumatic', chapter: 'EXTREMITIES', remedies: ['Act-r.', 'Alum.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Led.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-1-3', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - pain - tearing', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sanguin.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-4', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - pain - shooting', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bry.', 'Bary-c.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr.', 'Fluor.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-m.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-5', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - pain - stitching', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Aur.', 'Bry.', 'Bary-c.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-6', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - right side', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-7', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - left side', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-8', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - raising arm agg.', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-9', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - motion agg.', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Arn.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-1-10', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - stiffness', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-11', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - weakness', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-1-12', text: 'EXTREMITIES - UPPER LIMBS - Shoulder - dislocation', chapter: 'EXTREMITIES', remedies: ['Arn.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Led.', 'Rhus-t.', 'Ruta.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-2', text: 'EXTREMITIES - UPPER LIMBS - Arm', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Calc-s.', 'Calen.', 'Camph.', 'Canth.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Par.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Tab.', 'Thuj.', 'Valer.', 'Viol-t.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-2-1', text: 'EXTREMITIES - UPPER LIMBS - Arm - pain', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-2-2', text: 'EXTREMITIES - UPPER LIMBS - Arm - pain - tearing', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-2-3', text: 'EXTREMITIES - UPPER LIMBS - Arm - pain - aching', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-2-4', text: 'EXTREMITIES - UPPER LIMBS - Arm - pain - throbbing', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-3', text: 'EXTREMITIES - UPPER LIMBS - Elbow', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Calc-s.', 'Calen.', 'Caust.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Valer.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-3-1', text: 'EXTREMITIES - UPPER LIMBS - Elbow - pain', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-3-2', text: 'EXTREMITIES - UPPER LIMBS - Elbow - pain - rheumatic', chapter: 'EXTREMITIES', remedies: ['Act-r.', 'Alum.', 'Ang.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Led.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-3-3', text: 'EXTREMITIES - UPPER LIMBS - Elbow - stiffness', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ang.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-4', text: 'EXTREMITIES - UPPER LIMBS - Forearm', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-4-1', text: 'EXTREMITIES - UPPER LIMBS - Forearm - pain', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-4-2', text: 'EXTREMITIES - UPPER LIMBS - Forearm - pain - tearing', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-2-5', text: 'EXTREMITIES - UPPER LIMBS - Wrist', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-5-1', text: 'EXTREMITIES - UPPER LIMBS - Wrist - pain', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-5-2', text: 'EXTREMITIES - UPPER LIMBS - Wrist - pain - after sprain', chapter: 'EXTREMITIES', remedies: ['Arn.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Led.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Rhus-t.', 'Ruta.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-5-3', text: 'EXTREMITIES - UPPER LIMBS - Wrist - caries', chapter: 'EXTREMITIES', remedies: ['Aur.', 'Calc.', 'Carb-v.', 'Fluor.', 'Hep.', 'Kali-bi.', 'Lyc.', 'Mez.', 'Nit-ac.', 'Phos.', 'Sec.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-2-5-4', text: 'EXTREMITIES - UPPER LIMBS - Wrist - dropsical swelling', chapter: 'EXTREMITIES', remedies: ['Apis.', 'Ars.', 'Bry.', 'Calc.', 'Carb-v.', 'Dig.', 'Helleb.', 'Lyc.', 'Phos.', 'Sulph.'], grade: 1 },
      { id: 'ext-2-6', text: 'EXTREMITIES - UPPER LIMBS - Hand', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Canth.', 'Carb-an.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Crot-h.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Jug-r.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Par.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plat.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Valer.', 'Viol-t.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-6-1', text: 'EXTREMITIES - UPPER LIMBS - Hand - cold', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Ars.', 'Bov.', 'Calc.', 'Camph.', 'Carb-v.', 'Caust.', 'Chel.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-6-2', text: 'EXTREMITIES - UPPER LIMBS - Hand - hot', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Apis.', 'Ars.', 'Bry.', 'Canth.', 'Cham.', 'Con.', 'Dig.', 'Fluor.', 'Gels.', 'Lach.', 'Lyc.', 'Mag-c.', 'Merc.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Spong.', 'Sulph.'], grade: 1 },
      { id: 'ext-2-6-3', text: 'EXTREMITIES - UPPER LIMBS - Hand - sweating', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Bov.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Con.', 'Dig.', 'Dros.', 'Gels.', 'Hep.', 'Iod.', 'Lyc.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-6-4', text: 'EXTREMITIES - UPPER LIMBS - Hand - trembling', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Ars.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-6-5', text: 'EXTREMITIES - UPPER LIMBS - Hand - weakness', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-6-6', text: 'EXTREMITIES - UPPER LIMBS - Hand - swelling', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-7', text: 'EXTREMITIES - UPPER LIMBS - Fingers', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Canth.', 'Carb-v.', 'Caust.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Crot-h.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-7-1', text: 'EXTREMITIES - UPPER LIMBS - Fingers - pain', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sars.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-7-2', text: 'EXTREMITIES - UPPER LIMBS - Fingers - panaritium', chapter: 'EXTREMITIES', remedies: ['Apis.', 'Ars.', 'Bell.', 'Calc.', 'Carb-an.', 'Hep.', 'Lach.', 'Merc.', 'Nit-ac.', 'Sil.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-7-3', text: 'EXTREMITIES - UPPER LIMBS - Fingers - whitlow', chapter: 'EXTREMITIES', remedies: ['Apis.', 'Ars.', 'Bell.', 'Calc.', 'Carb-an.', 'Hep.', 'Lach.', 'Merc.', 'Nit-ac.', 'Sil.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-2-7-4', text: 'EXTREMITIES - UPPER LIMBS - Fingers - chilblains', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Ars.', 'Bov.', 'Carb-v.', 'Caust.', 'Lach.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.'], grade: 1 },
      { id: 'ext-2-7-5', text: 'EXTREMITIES - UPPER LIMBS - Fingers - cramping', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Bary-c.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.', 'Zinc.'], grade: 1 },
      { id: 'ext-2-7-6', text: 'EXTREMITIES - UPPER LIMBS - Fingers - cracking of joints', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Arg-n.', 'Bary-c.', 'Calc.', 'Carb-v.', 'Fluor.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-3', text: 'EXTREMITIES - LOWER LIMBS', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Canth.', 'Carb-v.', 'Caries', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Graph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Par.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Senec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Valer.', 'Viol-t.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-1', text: 'EXTREMITIES - LOWER LIMBS - Hip', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Valer.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-1-1', text: 'EXTREMITIES - LOWER LIMBS - Hip - pain', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Valer.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-1-2', text: 'EXTREMITIES - LOWER LIMBS - Hip - pain - rheumatic', chapter: 'EXTREMITIES', remedies: ['Act-r.', 'Alum.', 'Ang.', 'Aur.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Led.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-3-1-3', text: 'EXTREMITIES - LOWER LIMBS - Hip - pain - sciatica', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Arn.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Valer.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-1-4', text: 'EXTREMITIES - LOWER LIMBS - Hip - dislocation', chapter: 'EXTREMITIES', remedies: ['Arn.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Led.', 'Rhus-t.', 'Ruta.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.'], grade: 1 },
      { id: 'ext-3-2', text: 'EXTREMITIES - LOWER LIMBS - Thigh', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-2-1', text: 'EXTREMITIES - LOWER LIMBS - Thigh - pain', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3', text: 'EXTREMITIES - LOWER LIMBS - Knee', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Calen.', 'Camph.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lit.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3-1', text: 'EXTREMITIES - LOWER LIMBS - Knee - pain', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3-2', text: 'EXTREMITIES - LOWER LIMBS - Knee - pain - tearing', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-3-3-3', text: 'EXTREMITIES - LOWER LIMBS - Knee - pain - drawing', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3-4', text: 'EXTREMITIES - LOWER LIMBS - Knee - stiffness', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ang.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-3-3-5', text: 'EXTREMITIES - LOWER LIMBS - Knee - swelling', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3-6', text: 'EXTREMITIES - LOWER LIMBS - Knee - weakness', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-3-7', text: 'EXTREMITIES - LOWER LIMBS - Knee - clicking', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Arg-n.', 'Bary-c.', 'Calc.', 'Carb-v.', 'Fluor.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-3-4', text: 'EXTREMITIES - LOWER LIMBS - Leg', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-4-1', text: 'EXTREMITIES - LOWER LIMBS - Leg - cramps', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-4-2', text: 'EXTREMITIES - LOWER LIMBS - Leg - cramps - night', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-4-3', text: 'EXTREMITIES - LOWER LIMBS - Leg - cramps - calf', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-4-4', text: 'EXTREMITIES - LOWER LIMBS - Leg - varicose veins', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Alum.', 'Am-c.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Bry.', 'Calc.', 'Carb-ac.', 'Carb-v.', 'Caust.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Thuj.', 'Valer.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-4-5', text: 'EXTREMITIES - LOWER LIMBS - Leg - restlessness', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-5', text: 'EXTREMITIES - LOWER LIMBS - Ankle', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-5-1', text: 'EXTREMITIES - LOWER LIMBS - Ankle - pain', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-5-2', text: 'EXTREMITIES - LOWER LIMBS - Ankle - swelling', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-5-3', text: 'EXTREMITIES - LOWER LIMBS - Ankle - weakness', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-6', text: 'EXTREMITIES - LOWER LIMBS - Foot', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-6-1', text: 'EXTREMITIES - LOWER LIMBS - Foot - cold', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Ars.', 'Bov.', 'Calc.', 'Camph.', 'Carb-v.', 'Caust.', 'Chel.', 'Coff.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-6-2', text: 'EXTREMITIES - LOWER LIMBS - Foot - hot', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Apis.', 'Ars.', 'Bry.', 'Calc.', 'Canth.', 'Con.', 'Dig.', 'Fluor.', 'Gels.', 'Lach.', 'Lyc.', 'Mag-c.', 'Merc.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Spong.', 'Sulph.'], grade: 1 },
      { id: 'ext-3-6-3', text: 'EXTREMITIES - LOWER LIMBS - Foot - sweating', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ars.', 'Bov.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Con.', 'Dig.', 'Dros.', 'Gels.', 'Hep.', 'Iod.', 'Lyc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-6-4', text: 'EXTREMITIES - LOWER LIMBS - Foot - burning', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Ars.', 'Bov.', 'Bry.', 'Calc.', 'Camph.', 'Canth.', 'Carb-v.', 'Caust.', 'Con.', 'Dros.', 'Gels.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-6-5', text: 'EXTREMITIES - LOWER LIMBS - Foot - gout', chapter: 'EXTREMITIES', remedies: ['Apis.', 'Arn.', 'Aur.', 'Benz-ac.', 'Bell.', 'Bry.', 'Calc.', 'Caust.', 'Colch.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Guaj.', 'Kali-bi.', 'Led.', 'Lith.', 'Lyc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sabina', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.'], grade: 1 },
      { id: 'ext-3-6-6', text: 'EXTREMITIES - LOWER LIMBS - Foot - odorous', chapter: 'EXTREMITIES', remedies: ['Alum.', 'Ars.', 'Bov.', 'Bry.', 'Calc.', 'Con.', 'Hep.', 'Lyc.', 'Med.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'ext-3-7', text: 'EXTREMITIES - LOWER LIMBS - Toes', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Caust.', 'Chel.', 'Cimic.', 'Clem.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-7-1', text: 'EXTREMITIES - LOWER LIMBS - Toes - pain', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-7-2', text: 'EXTREMITIES - LOWER LIMBS - Toes - corns', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Ant-c.', 'Ars.', 'Benz-ac.', 'Bov.', 'Calc.', 'Carb-v.', 'Caust.', 'Con.', 'Ferr-p.', 'Fluor.', 'Graph.', 'Guaj.', 'Kali-bi.', 'Lyc.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.'], grade: 1 },
      { id: 'ext-3-7-3', text: 'EXTREMITIES - LOWER LIMBS - Toes - bunions', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Ferr-p.', 'Fluor.', 'Graph.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-3-7-4', text: 'EXTREMITIES - LOWER LIMBS - Toes - chilblains', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Ars.', 'Bov.', 'Carb-v.', 'Caust.', 'Lach.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sil.', 'Sulph.'], grade: 1 },
      { id: 'ext-4', text: 'EXTREMITIES - WEAKNESS', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Valer.', 'Viol-t.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-4-1', text: 'EXTREMITIES - WEAKNESS - upper limbs', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Guaj.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-4-2', text: 'EXTREMITIES - WEAKNESS - lower limbs', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-5', text: 'EXTREMITIES - PARALYSIS', chapter: 'EXTREMITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mur-ac.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Ox-ac.', 'Phos.', 'Phyt.', 'Plb.', 'Pod.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sanguin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Stram.', 'Sulph.', 'Syph.', 'Thuj.', 'Valer.', 'Viol-t.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-6', text: 'EXTREMITIES - TREMORING', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Arg-n.', 'Ars.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sep.', 'Sil.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'ext-7', text: 'EXTREMITIES - RESTLESSNESS', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Am-m.', 'Ang.', 'Apis.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Valer.', 'Xanth.', 'Zinc.'], grade: 1 },
      { id: 'ext-8', text: 'EXTREMITIES - NUMBNESS', chapter: 'EXTREMITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mur-ac.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
    ]
  }'''

# Insert before closing '];'
insert_text = '  ' + EXTREMITIES.replace('\n', '\n  ') + ','

# Find the last '  }' followed by '];'
pattern = r"\n  \}\n\];"
match = re.search(pattern, content)
if match:
    pos = match.start() + 1  # after the \n
    content = content[:pos] + '\n' + insert_text + '\n' + content[pos+1:]
    print("EXTREMITIES chapter added before closing ];")
else:
    print("Could not find closing ]; pattern!")

write_file(FILE_PATH, content)
print("Step 4 done: EXTREMITIES added")
