#!/usr/bin/env python3
"""Step 5b: Add GENERALITIES - fix insertion"""

import re

FILE_PATH = '/home/z/my-project/homeodesk-pro/src/kentRepertoryData.ts'

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

content = read_file(FILE_PATH)

GENERALITIES = """{
    id: 'generalities',
    chapter: 'GENERALITIES',
    rubrics: [
      { id: 'gen-1', text: 'GENERALITIES - FOOD and DRINKS', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agn.', 'Alum.', 'Am-c.', 'Ant-c.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dulc.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gels.', 'Graph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'gen-1-1', text: 'GENERALITIES - DESIRE - sweets', chapter: 'GENERALITIES', remedies: ['Arg-n.', 'Calc.', 'Carb-v.', 'Cham.', 'Con.', 'Croc.', 'Hep.', 'Iod.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Staph.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-2', text: 'GENERALITIES - DESIRE - sour', chapter: 'GENERALITIES', remedies: ['Ant-c.', 'Aur.', 'Bry.', 'Calc.', 'Caust.', 'Chin.', 'Coff.', 'Dulc.', 'Gels.', 'Hep.', 'Lyc.', 'Med.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.'], grade: 1 },
      { id: 'gen-1-3', text: 'GENERALITIES - DESIRE - salt', chapter: 'GENERALITIES', remedies: ['Aur.', 'Bry.', 'Calc.', 'Caust.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-4', text: 'GENERALITIES - DESIRE - spicy food', chapter: 'GENERALITIES', remedies: ['Arg-n.', 'Bry.', 'Calc.', 'Carb-v.', 'Carb-an.', 'Cham.', 'Con.', 'Gels.', 'Hep.', 'Kali-c.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Sep.', 'Sulph.'], grade: 1 },
      { id: 'gen-1-5', text: 'GENERALITIES - DESIRE - fatty food', chapter: 'GENERALITIES', remedies: ['Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Chel.', 'Con.', 'Hep.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Sep.', 'Sulph.'], grade: 1 },
      { id: 'gen-1-6', text: 'GENERALITIES - DESIRE - cold drinks', chapter: 'GENERALITIES', remedies: ['Acon.', 'Ars.', 'Bry.', 'Calc.', 'Camph.', 'Chin.', 'Crot-h.', 'Dros.', 'Gels.', 'Iod.', 'Kali-c.', 'Lyc.', 'Mag-c.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sep.', 'Sulph.', 'Thuj.'], grade: 1 },
      { id: 'gen-1-7', text: 'GENERALITIES - DESIRE - hot drinks', chapter: 'GENERALITIES', remedies: ['Aur.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Chel.', 'Chin.', 'Con.', 'Dros.', 'Ferr.', 'Gels.', 'Hep.', 'Kali-c.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sulph.'], grade: 1 },
      { id: 'gen-1-8', text: 'GENERALITIES - DESIRE - eggs', chapter: 'GENERALITIES', remedies: ['Arg-n.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Chel.', 'Croc.', 'Con.', 'Ferr.', 'Hep.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Sulph.'], grade: 1 },
      { id: 'gen-1-9', text: 'GENERALITIES - AVERSION - sweets', chapter: 'GENERALITIES', remedies: ['Ars.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Con.', 'Hep.', 'Iod.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-10', text: 'GENERALITIES - AVERSION - meat', chapter: 'GENERALITIES', remedies: ['Acon.', 'Ant-c.', 'Ars.', 'Bary-c.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Con.', 'Hep.', 'Iod.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-11', text: 'GENERALITIES - AVERSION - fat', chapter: 'GENERALITIES', remedies: ['Ars.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Chel.', 'Con.', 'Hep.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nux-v.', 'Phos.', 'Puls.', 'Sep.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-12', text: 'GENERALITIES - AVERSION - milk', chapter: 'GENERALITIES', remedies: ['Acon.', 'Ant-c.', 'Ars.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Con.', 'Hep.', 'Iod.', 'Kali-c.', 'Lyc.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Sulph.', 'Tub.'], grade: 1 },
      { id: 'gen-1-13', text: 'GENERALITIES - THIRST - increased', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Apis.', 'Arg-n.', 'Ars.', 'Bary-c.', 'Bell.', 'Bov.', 'Bry.', 'Calc.', 'Camph.', 'Canth.', 'Carb-v.', 'Carb-an.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Gels.', 'Guaj.', 'Iod.', 'Kali-c.', 'Lach.', 'Lyc.', 'Mag-c.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sec.', 'Sep.', 'Sil.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-1-14', text: 'GENERALITIES - THIRST - thirstlessness', chapter: 'GENERALITIES', remedies: ['Acon.', 'Alum.', 'Am-c.', 'Apis.', 'Arg-n.', 'Ars.', 'Bary-c.', 'Bell.', 'Bry.', 'Calc.', 'Camph.', 'Canth.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Gels.', 'Graph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-c.', 'Lach.', 'Led.', 'Lyc.', 'Mag-c.', 'Med.', 'Merc.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Rhus-t.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2', text: 'GENERALITIES - COLD - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2-1', text: 'GENERALITIES - HEAT - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Apis.', 'Arg-n.', 'Ars.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2-2', text: 'GENERALITIES - DAMP - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Camph.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2-3', text: 'GENERALITIES - DRY weather amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Con.', 'Dros.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2-4', text: 'GENERALITIES - STORM - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-2-5', text: 'GENERALITIES - OPEN air amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-3', text: 'GENERALITIES - MORNING - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-3-1', text: 'GENERALITIES - AFTERNOON - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-3-2', text: 'GENERALITIES - EVENING - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Coff.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-3-3', text: 'GENERALITIES - NIGHT - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Clem.', 'Con.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sabin.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-3-4', text: 'GENERALITIES - MIDNIGHT - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4', text: 'GENERALITIES - LYING - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-1', text: 'GENERALITIES - LYING - amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-2', text: 'GENERALITIES - LYING on left side', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-3', text: 'GENERALITIES - LYING on right side', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-4', text: 'GENERALITIES - SITTING - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-5', text: 'GENERALITIES - SITTING - amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-4-6', text: 'GENERALITIES - STANDING - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-5', text: 'GENERALITIES - MOTION - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-5-1', text: 'GENERALITIES - MOTION - amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-5-2', text: 'GENERALITIES - WALKING - agg.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-5-3', text: 'GENERALITIES - WALKING - amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-m.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-6', text: 'GENERALITIES - TOUCH - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Alum.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-6-1', text: 'GENERALITIES - PRESSURE - amel.', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-7', text: 'GENERALITIES - WEAKNESS', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-7-1', text: 'GENERALITIES - WEAKNESS - morning', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Con.', 'Dros.', 'Ferr-p.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-7-2', text: 'GENERALITIES - WEAKNESS - after eating', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-8', text: 'GENERALITIES - EMACIATION', chapter: 'GENERALITIES', remedies: ['Abrot.', 'Agn.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Tub.', 'Zinc.'], grade: 1 },
      { id: 'gen-8-1', text: 'GENERALITIES - EMACIATION - children', chapter: 'GENERALITIES', remedies: ['Abrot.', 'Agn.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Nat-m.', 'Nat-s.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Tub.', 'Zinc.'], grade: 1 },
      { id: 'gen-9', text: 'GENERALITIES - OBESITY', chapter: 'GENERALITIES', remedies: ['Agn.', 'Alum.', 'Am-c.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Calc-s.', 'Carb-v.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Kali-c.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Manc.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-10', text: 'GENERALITIES - CONVALESCENCE', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-11', text: 'GENERALITIES - SENSITIVENESS - to pain', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Cimic.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Spong.', 'Staph.', 'Sulph.', 'Syph.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-12', text: 'GENERALITIES - BLEEDING tendency', chapter: 'GENERALITIES', remedies: ['Acon.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Eup-per.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Merc.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phos-ac.', 'Phyt.', 'Plb.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-13', text: 'GENERALITIES - JAUNDICE', chapter: 'GENERALITIES', remedies: ['Acon.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Carb-v.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Phyt.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sars.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-14', text: 'GENERALITIES - EXCITEMENT - agg.', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Am-m.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-15', text: 'GENERALITIES - FRIGHT - effects of', chapter: 'GENERALITIES', remedies: ['Acon.', 'Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gels.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Op.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Stram.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-16', text: 'GENERALITIES - SUPPRESSION - of eruptions', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Ars.', 'Aur.', 'Bary-c.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Syph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-16-1', text: 'GENERALITIES - SUPPRESSION - of menses', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-n.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Chel.', 'Chin.', 'Cimic.', 'Con.', 'Dros.', 'Ferr.', 'Ferr-p.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Iod.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Mur-ac.', 'Nat-c.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
      { id: 'gen-16-2', text: 'GENERALITIES - SUPPRESSION - of perspiration', chapter: 'GENERALITIES', remedies: ['Agar.', 'Alum.', 'Am-c.', 'Ang.', 'Apis.', 'Arg-m.', 'Ars.', 'Aur.', 'Bary-c.', 'Bell.', 'Benz-ac.', 'Bov.', 'Bry.', 'Calc.', 'Caust.', 'Cham.', 'Chel.', 'Chin.', 'Cimic.', 'Coff.', 'Con.', 'Cupr.', 'Dros.', 'Ferr.', 'Fluor.', 'Gnaph.', 'Guaj.', 'Hep.', 'Kali-bi.', 'Lach.', 'Led.', 'Lil-t.', 'Lyc.', 'Mag-c.', 'Mag-m.', 'Med.', 'Mez.', 'Nat-m.', 'Nit-ac.', 'Nux-v.', 'Phos.', 'Puls.', 'Ran-b.', 'Rhus-t.', 'Ruta.', 'Sec.', 'Sep.', 'Sil.', 'Staph.', 'Sulph.', 'Tab.', 'Thuj.', 'Zinc.'], grade: 1 },
    ]
  }"""

# Replace the last }, with },\nGENERALITIES
# Current end: " },\n];\n\n// Generated..."
content = content.rstrip()

# Remove the trailing comment
lines = content.split('\n')
# Find the line with "};"
for i in range(len(lines)-1, -1, -1):
    if '];' in lines[i]:
        # Insert GENERALITIES before this line
        new_lines = lines[:i] + ['  ' + GENERALITIES.replace('\n', '\n  ') + ',', '']
        content = '\n'.join(new_lines)
        break

write_file(FILE_PATH, content)
print("Step 5b done: GENERALITIES added")
